-- 2026-06-24 SQL 探查「异步下载」：任务表(含文件BLOB) + 列表/下载接口资源登记 + 授权。
-- 用户点下载→后台线程跑SQL(无行限,SXSSF流式)→xlsx存DB(FILE_CONTENT)→列表轮询进度→成功点下载。

-- 1) 任务表（文件直接存库 BLOB）
CREATE TABLE IF NOT EXISTS SQL_PROBE_EXPORT_TASK (
  ID            VARCHAR(32)  NOT NULL COMMENT '任务ID(UUID去横线)',
  EMP_ID        VARCHAR(64)  NOT NULL COMMENT '发起人工号',
  SQL_TEXT      TEXT         NOT NULL COMMENT '规范化后的SQL',
  REMARK        VARCHAR(200)          COMMENT '执行原因',
  STATUS        VARCHAR(16)  NOT NULL COMMENT 'RUNNING/SUCCESS/FAILED',
  ROW_COUNT     INT                   COMMENT '导出行数',
  FILE_NAME     VARCHAR(200)          COMMENT '下载文件名',
  FILE_CONTENT  LONGBLOB              COMMENT '生成的 xlsx 文件字节',
  ERROR_MSG     VARCHAR(500)          COMMENT '失败原因',
  CREATED_TIME  DATETIME     NOT NULL COMMENT '创建时间',
  FINISHED_TIME DATETIME              COMMENT '完成时间',
  PRIMARY KEY (ID),
  KEY IDX_SPET_EMP_TIME (EMP_ID, CREATED_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL探查异步导出任务';

-- 2) 登记两个新接口资源（列表/下载），启用 STATUS=0
INSERT INTO PT_RESOURCE
  (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, ISMENU, MENU_ENDFLAG, MENU_RANK_NO, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER)
VALUES
  ('R_RPT_SQL_EXP_TASKS', '/api/reports/sql-probe/export/tasks', 'GET', 'SQL探查导出任务列表', 0, 0, 0, 'M_REPORT_SQL', 0, 'RPT', NOW(), 'seed'),
  ('R_RPT_SQL_EXP_DL', '/api/reports/sql-probe/export/*/download', 'GET', 'SQL探查导出文件下载', 0, 0, 0, 'M_REPORT_SQL', 0, 'RPT', NOW(), 'seed')
ON DUPLICATE KEY UPDATE RESOURCE_URL=VALUES(RESOURCE_URL), RESOURCE_METHOD=VALUES(RESOURCE_METHOD), STATUS=0;

-- 3) 把这两个资源授给"有 SQL 探查菜单(M_REPORT_SQL)"的所有角色（幂等）
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT REPLACE(UUID(),'-',''), r.ROLE_ID, n.RID, 'PLATFORM', NOW()
FROM (SELECT DISTINCT ROLE_ID FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='M_REPORT_SQL') r
CROSS JOIN (SELECT 'R_RPT_SQL_EXP_TASKS' RID UNION ALL SELECT 'R_RPT_SQL_EXP_DL') n
WHERE NOT EXISTS (SELECT 1 FROM PT_ROLE_RESOURCE x WHERE x.ROLE_ID=r.ROLE_ID AND x.RESOURCE_ID=n.RID);
