-- 2026-07-09 PERF_RUN_TASK 加 trigger_type（触发来源）列 + 复合索引，供任务监控页按重算过滤
-- 幂等：INFORMATION_SCHEMA 预检
SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERF_RUN_TASK' AND COLUMN_NAME = 'trigger_type');
SET @sql := IF(@col = 0,
  'ALTER TABLE `PERF_RUN_TASK` ADD COLUMN `trigger_type` varchar(20) DEFAULT NULL COMMENT ''触发来源：RECALC/SCHEDULED/MANUAL'' AFTER `task_type`',
  'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @idx := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PERF_RUN_TASK' AND INDEX_NAME = 'idx_type_trigger');
SET @sql2 := IF(@idx = 0,
  'ALTER TABLE `PERF_RUN_TASK` ADD KEY `idx_type_trigger` (`task_type`, `trigger_type`)',
  'SELECT 1');
PREPARE s2 FROM @sql2; EXECUTE s2; DEALLOCATE PREPARE s2;
