-- 红色引擎“任务处理”：授权支部书记处理直接四大维度材料上报。
-- 仅新增缺失的角色-资源关系；角色或资源停用、缺失时不写入。
START TRANSACTION;

INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT
    MD5(CONCAT(r.ROLE_ID, '#', x.RESOURCE_ID)),
    r.ROLE_ID,
    x.RESOURCE_ID,
    'RE',
    NOW()
FROM PT_ROLE r
CROSS JOIN (
    SELECT 'P_RE_REVIEW_Q' AS RESOURCE_ID
    UNION ALL SELECT 'P_RE_REVIEW_APPR'
    UNION ALL SELECT 'P_RE_REVIEW_REJ'
) x
INNER JOIN PT_RESOURCE p
        ON p.RESOURCE_ID = x.RESOURCE_ID
       AND p.STATUS = 0
WHERE r.ROLE_CODE = 'R_RE_SECR'
  AND r.RECORD_STATUS = 0
  AND NOT EXISTS (
      SELECT 1
      FROM PT_ROLE_RESOURCE rr
      WHERE rr.ROLE_ID = r.ROLE_ID
        AND rr.RESOURCE_ID = x.RESOURCE_ID
  );

COMMIT;
