-- 客户营销触达菜单去重：触达任务管理与触达记录一览实际使用同一页面，
-- 按 V2 Demo 统一为单一“触达任务一览”入口。可重复执行。
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE PT_RESOURCE
SET PARENT_RESOURCE_ID = 'M_MKT_TOUCH_OV',
    UPDATE_USER = 'customer-menu-dedupe-0811',
    REMARK = '触达任务一览'
WHERE RESOURCE_ID = 'C_TOUCH_LOG_LIST';

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'M_MKT_TOUCH_LOG';
DELETE FROM PT_RESOURCE WHERE RESOURCE_ID = 'M_MKT_TOUCH_LOG';

UPDATE PT_RESOURCE
SET RESOURCE_URL = '/touches/overview',
    MENU_NAME = '触达任务一览',
    UPDATE_USER = 'customer-menu-dedupe-0811',
    REMARK = '触达任务管理视图'
WHERE RESOURCE_ID = 'M_MKT_TOUCH_OV';

UPDATE PT_RESOURCE SET MENU_RANK_NO = 11 WHERE RESOURCE_ID = 'M_MKT_TRANSFER';

COMMIT;

SELECT RESOURCE_ID, RESOURCE_URL, MENU_NAME, MENU_RANK_NO, PARENT_RESOURCE_ID
FROM PT_RESOURCE
WHERE PARENT_RESOURCE_ID = 'M_GROUP_MARKETING'
ORDER BY MENU_RANK_NO, RESOURCE_ID;
