-- 客户标签管理：注册批量禁用、批量删除接口资源，并继承既有标签操作权限。
START TRANSACTION;

INSERT INTO PT_RESOURCE
  (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL,
   MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE,
   CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES
  ('C_TAG_BATCH_DISABLE', '/api/tags/batch-disable', 'POST', '客户标签批量禁用', NULL,
   0, 0, '0', 'M_MKT_TAGS', 0, 'CUSTOMER', NOW(), 'customer-tag-batch-0811', NOW(), 'customer-tag-batch-0811', '多选批量禁用'),
  ('C_TAG_BATCH_DELETE', '/api/tags/batch-delete', 'POST', '客户标签批量删除', NULL,
   0, 0, '0', 'M_MKT_TAGS', 0, 'CUSTOMER', NOW(), 'customer-tag-batch-0811', NOW(), 'customer-tag-batch-0811', '多选批量软删除')
ON DUPLICATE KEY UPDATE
  RESOURCE_URL = VALUES(RESOURCE_URL),
  RESOURCE_METHOD = VALUES(RESOURCE_METHOD),
  MENU_NAME = VALUES(MENU_NAME),
  PARENT_RESOURCE_ID = VALUES(PARENT_RESOURCE_ID),
  STATUS = 0,
  UPDATE_TIME = NOW(),
  UPDATE_USER = 'customer-tag-batch-0811';

-- 批量禁用继承单标签启停权限；批量删除继承标签编辑权限。
INSERT IGNORE INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT LOWER(MD5(CONCAT(ROLE_ID, ':C_TAG_BATCH_DISABLE'))), ROLE_ID,
       'C_TAG_BATCH_DISABLE', SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE
WHERE RESOURCE_ID = 'C_TAG_STATUS';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT LOWER(MD5(CONCAT(ROLE_ID, ':C_TAG_BATCH_DELETE'))), ROLE_ID,
       'C_TAG_BATCH_DELETE', SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE
WHERE RESOURCE_ID = 'C_TAG_UPDATE';

COMMIT;
