-- 客户营销业务角色、资源、数据范围与线索审批候选人对齐。
--
-- 角色口径：
--   1. 新增 CUST_MARKETING_MANAGER 作为“客户营销-客户经理”，不改名、不扩权既有 R_RM（机构员工）。
--   2. 新增 CUST_LEAD_APPROVER 作为“客户营销-线索审批”。
--   3. 线索两个审批节点保留原候选角色，并追加 CUST_LEAD_APPROVER 与 SYS_ADMIN。
--   4. 同步为已生成但尚未签收的在途线索任务补候选组；不修改 PT_USER_ROLE，不把角色擅自分配给用户。
--
-- 前置条件：2026-08-11 客户营销一期、三期资源脚本以及 workflow 基线已经执行。
-- 脚本可重复执行；正式库执行仍须遵守仓库数据库验证门禁。

SET NAMES utf8mb4;
START TRANSACTION;

-- 新增两个客户营销专用角色。
INSERT INTO PT_ROLE
    (ROLE_ID, ROLE_CODE, ROLE_CHNAME, RECORD_STATUS, SYS_CODE,
     CREATE_USER, UPDATE_USER, REMARK)
VALUES
    ('R_CUST_MARKETING_MANAGER', 'CUST_MARKETING_MANAGER', '客户营销-客户经理', 0, 'PLATFORM',
     'customer-role-0813', 'customer-role-0813', '客户营销客户经理角色'),
    ('R_CUST_LEAD_APPROVER', 'CUST_LEAD_APPROVER', '客户营销-线索审批', 0, 'PLATFORM',
     'customer-role-0813', 'customer-role-0813', '客户营销线索审批角色') AS new
ON DUPLICATE KEY UPDATE
    ROLE_CHNAME = new.ROLE_CHNAME,
    RECORD_STATUS = new.RECORD_STATUS,
    SYS_CODE = new.SYS_CODE,
    UPDATE_USER = new.UPDATE_USER,
    REMARK = new.REMARK;

-- 客户经理：七个业务页面及页面当前实际调用的接口资源。
-- 跨机构营销不授予 approve/reject；该角色只能校验、发起和查看本人申请。
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE)
SELECT MD5(CONCAT(r.ROLE_ID, '#', x.RESOURCE_ID)), r.ROLE_ID, x.RESOURCE_ID, 'CUSTOMER'
FROM PT_ROLE r
JOIN (
    SELECT 'CUST_MARKETING_MANAGER' AS ROLE_CODE, 'M_GROUP_MARKETING' AS RESOURCE_ID
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_CUST_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_LEAD_ENTRY'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_POOL_AVAIL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_POOL_CLAIM'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_CROSS_ORG'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_TOUCH_MINE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'M_MKT_TRANSFER'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CUST_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CUST_EXPORT'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CUST_DETAIL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_CREATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_OWNER_Q'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_UPDATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_DELETE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_SUBMIT'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_LEAD_DETAIL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TAG_ENABLED'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_POOL_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CLAIM_CREATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CLAIM_MINE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CLAIM_START'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CLAIM_RETOUCH'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CROSS_VALIDATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CROSS_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CROSS_CREATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_CROSS_DETAIL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_MINE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_DETAIL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_LOG_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_LOG_ADD'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_SUCCESS'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TOUCH_CANCEL'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TRANSFER_LIST'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TRANSFER_CREATE'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'C_TRANSFER_CAND'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'G_DICT_ITEMS'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'G_FILE_UPLOAD'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'G_FILE_DOWNLOAD'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'RES_PTL_ADDR_SRCH'
) x ON x.ROLE_CODE = r.ROLE_CODE
JOIN PT_RESOURCE res ON res.RESOURCE_ID = x.RESOURCE_ID AND res.STATUS = 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_ROLE_RESOURCE rr
    WHERE rr.ROLE_ID = r.ROLE_ID AND rr.RESOURCE_ID = x.RESOURCE_ID
);

-- 线索审批：只开放线索审批菜单、审批页查询/导出以及工作流通过、驳回。
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE)
SELECT MD5(CONCAT(r.ROLE_ID, '#', x.RESOURCE_ID)), r.ROLE_ID, x.RESOURCE_ID, 'CUSTOMER'
FROM PT_ROLE r
JOIN (
    SELECT 'CUST_LEAD_APPROVER' AS ROLE_CODE, 'M_GROUP_MARKETING' AS RESOURCE_ID
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'M_MKT_LEAD_APPR'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'C_LEAD_APPR_LIST'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'C_LEAD_APPR_DET'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'C_LEAD_APPR_EXP'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'W_TASK_APPROVE'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'W_TASK_REJECT'
) x ON x.ROLE_CODE = r.ROLE_CODE
JOIN PT_RESOURCE res ON res.RESOURCE_ID = x.RESOURCE_ID AND res.STATUS = 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_ROLE_RESOURCE rr
    WHERE rr.ROLE_ID = r.ROLE_ID AND rr.RESOURCE_ID = x.RESOURCE_ID
);

-- 线索审批采用候选角色直接办理，移除旧版已授予的通用任务领取权限。
DELETE rr
FROM PT_ROLE_RESOURCE rr
JOIN PT_ROLE r ON r.ROLE_ID = rr.ROLE_ID
WHERE r.ROLE_CODE = 'CUST_LEAD_APPROVER'
  AND rr.RESOURCE_ID = 'W_TASK_CLAIM';

-- 页面涉及的业务数据范围。客户经理已有的范围也用幂等更新保持明确口径。
INSERT INTO PT_ROLE_BIZ_SCOPE
    (ID, ROLE_ID, BIZ_TYPE, DATA_SCOPE, RECORD_STATUS, CREATE_USER, UPDATE_USER, REMARK)
SELECT MD5(CONCAT(r.ROLE_ID, '#', s.BIZ_TYPE)), r.ROLE_ID,
       s.BIZ_TYPE, s.DATA_SCOPE, 0, 'customer-role-0813', 'customer-role-0813', s.REMARK
FROM PT_ROLE r
JOIN (
    SELECT 'CUST_MARKETING_MANAGER' AS ROLE_CODE, 'CUSTOMER' AS BIZ_TYPE, 'ALL' AS DATA_SCOPE, '客户营销客户经理客户范围' AS REMARK
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'LEAD', 'ALL', '客户营销客户经理线索范围'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'CUSTOMER_POOL', 'ALL', '客户营销客户经理公开线索池范围'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'CLAIM', 'SELF_ASSIGNED', '客户营销客户经理本人认领范围'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'TOUCH_TASK', 'SELF_ASSIGNED', '客户营销客户经理本人触达任务范围'
    UNION ALL SELECT 'CUST_MARKETING_MANAGER', 'CROSS_ORG_MARKETING', 'SELF_CREATED', '客户营销客户经理本人跨机构申请范围'
    UNION ALL SELECT 'CUST_LEAD_APPROVER', 'LEAD', 'ALL', '客户营销线索审批全量待办范围'
) s ON s.ROLE_CODE = r.ROLE_CODE
ON DUPLICATE KEY UPDATE
    DATA_SCOPE = VALUES(DATA_SCOPE),
    RECORD_STATUS = 0,
    UPDATE_USER = 'customer-role-0813',
    REMARK = VALUES(REMARK);

-- 新流程实例：保留原审批角色，并让专职审批角色和系统管理员都成为候选人。
UPDATE WF_NODE_CANDIDATE_CONF
SET candidate_type = 'ROLE',
    candidate_value = '["BRANCH_HEAD","CUST_LEAD_APPROVER","SYS_ADMIN"]',
    updated_time = CURRENT_TIMESTAMP
WHERE process_definition_key = 'lead_approve_v1'
  AND node_key = 'branch_manager_approve';

UPDATE WF_NODE_CANDIDATE_CONF
SET candidate_type = 'ROLE',
    candidate_value = '["CORP_DEPT","RETAIL_DEPT","CUST_LEAD_APPROVER","SYS_ADMIN"]',
    updated_time = CURRENT_TIMESTAMP
WHERE process_definition_key = 'lead_approve_v1'
  AND node_key = 'hq_review';

-- 已经创建且尚未签收的线索任务不会重新触发 TaskAssignmentListener，需同步补运行态和历史身份链接。
DROP TEMPORARY TABLE IF EXISTS TMP_ACTIVE_LEAD_APPROVAL_TASK;
CREATE TEMPORARY TABLE TMP_ACTIVE_LEAD_APPROVAL_TASK AS
SELECT t.ID_ AS TASK_ID_, t.PROC_INST_ID_, t.PROC_DEF_ID_
FROM ACT_RU_TASK t
JOIN BIZ_PROCESS_MAP bpm ON bpm.process_instance_id = t.PROC_INST_ID_
WHERE bpm.biz_type = 'LEAD'
  AND bpm.process_definition_key = 'lead_approve_v1'
  AND bpm.process_status = 'RUNNING'
  AND t.ASSIGNEE_ IS NULL
  AND t.TASK_DEF_KEY_ IN ('branch_manager_approve', 'hq_review');

INSERT INTO ACT_RU_IDENTITYLINK
    (ID_, REV_, GROUP_ID_, TYPE_, USER_ID_, TASK_ID_, PROC_INST_ID_, PROC_DEF_ID_)
SELECT UUID(), 1, g.GROUP_ID_, 'candidate', NULL, t.TASK_ID_, NULL, NULL
FROM TMP_ACTIVE_LEAD_APPROVAL_TASK t
CROSS JOIN (
    SELECT 'ROLE:CUST_LEAD_APPROVER' AS GROUP_ID_
    UNION ALL SELECT 'ROLE:SYS_ADMIN'
) g
WHERE NOT EXISTS (
    SELECT 1 FROM ACT_RU_IDENTITYLINK il
    WHERE il.TASK_ID_ = t.TASK_ID_
      AND il.TYPE_ = 'candidate'
      AND il.GROUP_ID_ = g.GROUP_ID_
);

INSERT INTO ACT_HI_IDENTITYLINK
    (ID_, GROUP_ID_, TYPE_, USER_ID_, TASK_ID_, CREATE_TIME_, PROC_INST_ID_)
SELECT ru.ID_, ru.GROUP_ID_, ru.TYPE_, ru.USER_ID_, ru.TASK_ID_, CURRENT_TIMESTAMP(3), NULL
FROM ACT_RU_IDENTITYLINK ru
JOIN TMP_ACTIVE_LEAD_APPROVAL_TASK t ON t.TASK_ID_ = ru.TASK_ID_
WHERE ru.GROUP_ID_ IN ('ROLE:CUST_LEAD_APPROVER', 'ROLE:SYS_ADMIN')
  AND NOT EXISTS (
      SELECT 1 FROM ACT_HI_IDENTITYLINK hi WHERE hi.ID_ = ru.ID_
  );

DROP TEMPORARY TABLE TMP_ACTIVE_LEAD_APPROVAL_TASK;
COMMIT;

-- 验收查询 1：两角色的菜单和接口资源。
SELECT r.ROLE_CODE, r.ROLE_CHNAME, res.RESOURCE_ID, res.MENU_NAME,
       res.RESOURCE_URL, res.RESOURCE_METHOD, res.PARENT_RESOURCE_ID
FROM PT_ROLE r
JOIN PT_ROLE_RESOURCE rr ON rr.ROLE_ID = r.ROLE_ID
JOIN PT_RESOURCE res ON res.RESOURCE_ID = rr.RESOURCE_ID
WHERE r.ROLE_CODE IN ('CUST_MARKETING_MANAGER', 'CUST_LEAD_APPROVER')
  AND (res.RESOURCE_ID = 'M_GROUP_MARKETING'
       OR res.PARENT_RESOURCE_ID LIKE 'M_MKT_%'
       OR res.RESOURCE_ID LIKE 'M_MKT_%')
ORDER BY r.ROLE_CODE, res.ISMENU DESC, res.MENU_RANK_NO, res.RESOURCE_ID;

-- 验收查询 2：线索审批候选配置与当前在途任务候选组。
SELECT process_definition_key, node_key, candidate_type, candidate_value
FROM WF_NODE_CANDIDATE_CONF
WHERE process_definition_key = 'lead_approve_v1'
ORDER BY node_key;

SELECT t.ID_ AS task_id, ANY_VALUE(t.TASK_DEF_KEY_) AS task_def_key,
       ANY_VALUE(t.NAME_) AS task_name, ANY_VALUE(t.ASSIGNEE_) AS assignee,
       GROUP_CONCAT(DISTINCT il.GROUP_ID_ ORDER BY il.GROUP_ID_) AS candidate_groups
FROM ACT_RU_TASK t
JOIN BIZ_PROCESS_MAP bpm ON bpm.process_instance_id = t.PROC_INST_ID_
LEFT JOIN ACT_RU_IDENTITYLINK il ON il.TASK_ID_ = t.ID_ AND il.TYPE_ = 'candidate'
WHERE bpm.biz_type = 'LEAD'
  AND bpm.process_definition_key = 'lead_approve_v1'
  AND bpm.process_status = 'RUNNING'
GROUP BY t.ID_;
