-- PT_RESOURCE 登记 KPI 方案指标下拉接口 GET /api/perf/kpi-score/scheme-metrics（沿用 P_PERF_KPI_SCORE 角色集）
INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'P_PERF_KPISCORE_SM','/api/perf/kpi-score/scheme-metrics','GET','KPI方案指标下拉',0,0,0,'M_PERF_KPI_RULES',0,'PERF',NOW(),'seed',NOW(),'seed','kpi-scheme-metrics'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='P_PERF_KPISCORE_SM');

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_KPISCORE_SM';
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT UPPER(SUBSTRING(REPLACE(UUID(),'-',''),1,32)), s.ROLE_ID, 'P_PERF_KPISCORE_SM', s.SYS_CODE, NOW()
FROM (SELECT ROLE_ID, SYS_CODE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_KPI_SCORE') s;
