-- 2026-06-17 数据导入：登记「批次列表」与「源文件下载」两个新端点到 PT_RESOURCE，
-- 角色授权沿用既有「导入批次详情」资源 P_PERF_IMP_BTC_GET 的角色集（谁能看批次详情，谁就能列表 + 下载源文件）。
-- 父菜单 M_PERF_IMPORT（/perf/import 数据导入）。schema 变更走 SQL 直接执行（禁 Flyway）。

-- 1) GET /api/perf/import/batches —— 分页列表（@BizAuth PERF_CONFIG/LIST）
INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'P_PERF_IMP_BTC_LIST','/api/perf/import/batches','GET','导入批次列表',0,0,0,'M_PERF_IMPORT',0,'PERF',NOW(),'seed',NOW(),'seed','2026-06-17 导入列表落库'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_BTC_LIST');

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_BTC_LIST';
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT UPPER(SUBSTRING(REPLACE(UUID(),'-',''),1,32)), s.ROLE_ID, 'P_PERF_IMP_BTC_LIST', s.SYS_CODE, NOW()
FROM (SELECT ROLE_ID, SYS_CODE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_BTC_GET') s;

-- 2) GET /api/perf/import/batches/*/source-file —— 源文件下载（@BizAuth PERF_CONFIG/EXPORT）
INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'P_PERF_IMP_SRC_DL','/api/perf/import/batches/*/source-file','GET','导入源文件下载',0,0,0,'M_PERF_IMPORT',0,'PERF',NOW(),'seed',NOW(),'seed','2026-06-17 导入源文件下载'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_SRC_DL');

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_SRC_DL';
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT UPPER(SUBSTRING(REPLACE(UUID(),'-',''),1,32)), s.ROLE_ID, 'P_PERF_IMP_SRC_DL', s.SYS_CODE, NOW()
FROM (SELECT ROLE_ID, SYS_CODE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='P_PERF_IMP_BTC_GET') s;
