START TRANSACTION;

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL,
     MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS,
     SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT
    'M_MKT_TOUCH_LIMIT', '/customers/touch-limits', 'MENU', '客户触达周期管理', NULL,
    12, 1, '1', 'M_GROUP_MARKETING', 0,
    'PLATFORM', NOW(), 'SYSTEM', NOW(), 'SYSTEM', '客户标签触达周期与次数上限'
WHERE NOT EXISTS (
    SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID = 'M_MKT_TOUCH_LIMIT'
);

UPDATE PT_RESOURCE
SET RESOURCE_URL = '/customers/touch-limits',
    RESOURCE_METHOD = 'MENU',
    MENU_NAME = '客户触达周期管理',
    MENU_RANK_NO = 12,
    ISMENU = 1,
    MENU_ENDFLAG = '1',
    PARENT_RESOURCE_ID = 'M_GROUP_MARKETING',
    STATUS = 0,
    SYS_CODE = 'PLATFORM',
    UPDATE_TIME = NOW(),
    UPDATE_USER = 'SYSTEM',
    REMARK = '客户标签触达周期与次数上限'
WHERE RESOURCE_ID = 'M_MKT_TOUCH_LIMIT';

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL,
     MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS,
     SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT
    'C_TOUCH_LIMIT_LIST', '/api/touch-limit-rules', 'GET', '查询触达周期规则', NULL,
    0, 0, '0', 'M_MKT_TOUCH_LIMIT', 0,
    'PLATFORM', NOW(), 'SYSTEM', NOW(), 'SYSTEM', '按客户标签分页查询规则'
WHERE NOT EXISTS (
    SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID = 'C_TOUCH_LIMIT_LIST'
);

UPDATE PT_RESOURCE
SET RESOURCE_URL = '/api/touch-limit-rules',
    RESOURCE_METHOD = 'GET',
    MENU_NAME = '查询触达周期规则',
    ISMENU = 0,
    MENU_ENDFLAG = '0',
    PARENT_RESOURCE_ID = 'M_MKT_TOUCH_LIMIT',
    STATUS = 0,
    SYS_CODE = 'PLATFORM',
    UPDATE_TIME = NOW(),
    UPDATE_USER = 'SYSTEM',
    REMARK = '按客户标签分页查询规则'
WHERE RESOURCE_ID = 'C_TOUCH_LIMIT_LIST';

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL,
     MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS,
     SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT
    'C_TOUCH_LIMIT_UPD', '/api/touch-limit-rules/*', 'PUT', '修改触达周期规则', NULL,
    0, 0, '0', 'M_MKT_TOUCH_LIMIT', 0,
    'PLATFORM', NOW(), 'SYSTEM', NOW(), 'SYSTEM', '修改单个客户标签规则'
WHERE NOT EXISTS (
    SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID = 'C_TOUCH_LIMIT_UPD'
);

UPDATE PT_RESOURCE
SET RESOURCE_URL = '/api/touch-limit-rules/*',
    RESOURCE_METHOD = 'PUT',
    MENU_NAME = '修改触达周期规则',
    ISMENU = 0,
    MENU_ENDFLAG = '0',
    PARENT_RESOURCE_ID = 'M_MKT_TOUCH_LIMIT',
    STATUS = 0,
    SYS_CODE = 'PLATFORM',
    UPDATE_TIME = NOW(),
    UPDATE_USER = 'SYSTEM',
    REMARK = '修改单个客户标签规则'
WHERE RESOURCE_ID = 'C_TOUCH_LIMIT_UPD';

INSERT INTO PT_ROLE_RESOURCE
    (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT
    REPLACE(UUID(), '-', ''), ROLE_ID, RESOURCE_ID, 'PLATFORM', NOW()
FROM PT_ROLE
CROSS JOIN PT_RESOURCE
WHERE ROLE_CODE = 'SYS_ADMIN'
  AND PT_ROLE.SYS_CODE = 'PLATFORM'
  AND PT_RESOURCE.SYS_CODE = 'PLATFORM'
  AND RESOURCE_ID IN ('M_MKT_TOUCH_LIMIT', 'C_TOUCH_LIMIT_LIST', 'C_TOUCH_LIMIT_UPD')
  AND NOT EXISTS (
      SELECT 1
      FROM PT_ROLE_RESOURCE
      WHERE PT_ROLE_RESOURCE.ROLE_ID = PT_ROLE.ROLE_ID
        AND PT_ROLE_RESOURCE.RESOURCE_ID = PT_RESOURCE.RESOURCE_ID
        AND PT_ROLE_RESOURCE.SYS_CODE = 'PLATFORM'
  );

COMMIT;
