-- =====================================================================
-- 任务转交待认领 六端点 PT_RESOURCE + 角色绑定（workflow-monitor-transfer Task 12）
-- TaskTransferController：
--   发起  POST /api/workflow/monitor/tasks/{taskId}/transfer  RES_WF_TRF_INIT
--   收件箱 GET  /api/workflow/transfers/inbox                  RES_WF_TRF_INBOX
--   认领  POST /api/workflow/transfers/{id}/accept             RES_WF_TRF_ACCEPT
--   拒绝  POST /api/workflow/transfers/{id}/decline            RES_WF_TRF_DECLINE
--   发件箱 GET  /api/workflow/transfers/outbox                  RES_WF_TRF_OUTBOX
--   撤回  POST /api/workflow/transfers/{id}/cancel             RES_WF_TRF_CANCEL
--
-- 角色绑定口径：
--   发起端点挂在监控域下，鉴权对齐 RES_WF_MONITOR_LIST/M_SYS_WF_MONITOR
--     （秘书岗=231，分行行长=2，见 2026-07-13-workflow-monitor-menu.sql）。
--   收件箱/认领/拒绝/发件箱/撤回 5 个端点的接收人可以是任意具备任务办理角色的人，不限
--     秘书岗/行长——绑定口径对齐 LIVE DB 当前 /api/workflow/tasks* 系列资源
--     （W_TASK_APPROVE 等）已绑定的角色集合（26 个角色：1,2,3,4,5,7,17,128,129,130,148,
--     149,208,229,230,231,232,233,234,235,236,237,238,239,240,241，经
--     `SELECT DISTINCT ROLE_ID FROM PT_ROLE_RESOURCE prr JOIN PT_RESOURCE pr ON ...
--      WHERE pr.RESOURCE_URL LIKE '/api/workflow/tasks%'` 实测确认），
--     任何当前能办理任务的角色都能看见/认领/拒绝转交。
--
-- 幂等：先删同名行再插入，可重复执行。仅执行库 yiti（dev）。
-- 执行前已用 mysqldump 备份 PT_RESOURCE / PT_ROLE_RESOURCE 到
--   docs/superpowers/sql/backup/2026-07-13-yiti-pt-resource-before-transfer-controller.sql
-- =====================================================================

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID IN
  ('RES_WF_TRF_INIT','RES_WF_TRF_INBOX','RES_WF_TRF_ACCEPT','RES_WF_TRF_DECLINE','RES_WF_TRF_OUTBOX','RES_WF_TRF_CANCEL');
DELETE FROM PT_RESOURCE WHERE RESOURCE_ID IN
  ('RES_WF_TRF_INIT','RES_WF_TRF_INBOX','RES_WF_TRF_ACCEPT','RES_WF_TRF_DECLINE','RES_WF_TRF_OUTBOX','RES_WF_TRF_CANCEL');

INSERT INTO PT_RESOURCE
  (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL, MENU_RANK_NO,
   ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, REMARK)
VALUES
  ('RES_WF_TRF_INIT',    '/api/workflow/monitor/tasks/*/transfer', 'POST', '转交发起',   NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12'),
  ('RES_WF_TRF_INBOX',   '/api/workflow/transfers/inbox',          'GET',  '转交收件箱', NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12'),
  ('RES_WF_TRF_ACCEPT',  '/api/workflow/transfers/*/accept',       'POST', '转交认领',   NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12'),
  ('RES_WF_TRF_DECLINE', '/api/workflow/transfers/*/decline',      'POST', '转交拒绝',   NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12'),
  ('RES_WF_TRF_OUTBOX',  '/api/workflow/transfers/outbox',         'GET',  '转交发件箱', NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12'),
  ('RES_WF_TRF_CANCEL',  '/api/workflow/transfers/*/cancel',       'POST', '转交撤回',   NULL, 0, 0, '0', NULL, 0, 'PLATFORM', NOW(), 'wf-transfer-2026-07-13', 'v1 workflow-monitor-transfer Task12');

-- 发起端点：秘书岗(231)/分行行长(2)
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME) VALUES
  ('WFTRF_231_INIT','231','RES_WF_TRF_INIT','PLATFORM',NOW()),
  ('WFTRF_2_INIT','2','RES_WF_TRF_INIT','PLATFORM',NOW());

-- 收件箱/认领/拒绝/发件箱/撤回：26 个既有任务办理角色 x 5 端点 = 130 行
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME) VALUES
  ('WFTRF_1_INB','1','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_1_ACC','1','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_1_DEC','1','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_1_OUT','1','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_1_CAN','1','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_2_INB','2','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_2_ACC','2','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_2_DEC','2','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_2_OUT','2','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_2_CAN','2','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_3_INB','3','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_3_ACC','3','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_3_DEC','3','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_3_OUT','3','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_3_CAN','3','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_4_INB','4','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_4_ACC','4','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_4_DEC','4','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_4_OUT','4','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_4_CAN','4','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_5_INB','5','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_5_ACC','5','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_5_DEC','5','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_5_OUT','5','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_5_CAN','5','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_7_INB','7','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_7_ACC','7','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_7_DEC','7','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_7_OUT','7','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_7_CAN','7','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_17_INB','17','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_17_ACC','17','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_17_DEC','17','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_17_OUT','17','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_17_CAN','17','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_128_INB','128','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_128_ACC','128','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_128_DEC','128','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_128_OUT','128','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_128_CAN','128','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_129_INB','129','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_129_ACC','129','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_129_DEC','129','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_129_OUT','129','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_129_CAN','129','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_130_INB','130','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_130_ACC','130','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_130_DEC','130','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_130_OUT','130','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_130_CAN','130','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_148_INB','148','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_148_ACC','148','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_148_DEC','148','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_148_OUT','148','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_148_CAN','148','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_149_INB','149','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_149_ACC','149','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_149_DEC','149','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_149_OUT','149','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_149_CAN','149','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_208_INB','208','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_208_ACC','208','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_208_DEC','208','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_208_OUT','208','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_208_CAN','208','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_229_INB','229','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_229_ACC','229','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_229_DEC','229','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_229_OUT','229','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_229_CAN','229','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_230_INB','230','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_230_ACC','230','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_230_DEC','230','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_230_OUT','230','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_230_CAN','230','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_231_INB','231','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_231_ACC','231','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_231_DEC','231','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_231_OUT','231','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_231_CAN','231','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_232_INB','232','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_232_ACC','232','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_232_DEC','232','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_232_OUT','232','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_232_CAN','232','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_233_INB','233','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_233_ACC','233','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_233_DEC','233','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_233_OUT','233','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_233_CAN','233','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_234_INB','234','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_234_ACC','234','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_234_DEC','234','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_234_OUT','234','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_234_CAN','234','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_235_INB','235','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_235_ACC','235','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_235_DEC','235','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_235_OUT','235','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_235_CAN','235','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_236_INB','236','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_236_ACC','236','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_236_DEC','236','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_236_OUT','236','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_236_CAN','236','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_237_INB','237','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_237_ACC','237','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_237_DEC','237','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_237_OUT','237','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_237_CAN','237','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_238_INB','238','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_238_ACC','238','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_238_DEC','238','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_238_OUT','238','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_238_CAN','238','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_239_INB','239','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_239_ACC','239','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_239_DEC','239','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_239_OUT','239','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_239_CAN','239','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_240_INB','240','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_240_ACC','240','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_240_DEC','240','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_240_OUT','240','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_240_CAN','240','RES_WF_TRF_CANCEL','PLATFORM',NOW()),
  ('WFTRF_241_INB','241','RES_WF_TRF_INBOX','PLATFORM',NOW()),
  ('WFTRF_241_ACC','241','RES_WF_TRF_ACCEPT','PLATFORM',NOW()),
  ('WFTRF_241_DEC','241','RES_WF_TRF_DECLINE','PLATFORM',NOW()),
  ('WFTRF_241_OUT','241','RES_WF_TRF_OUTBOX','PLATFORM',NOW()),
  ('WFTRF_241_CAN','241','RES_WF_TRF_CANCEL','PLATFORM',NOW());

-- ── 验证 ────────────────────────────────────────────────────
SELECT RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, ISMENU FROM PT_RESOURCE WHERE RESOURCE_ID LIKE 'RES_WF_TRF_%' ORDER BY RESOURCE_ID;
SELECT RESOURCE_ID, COUNT(*) AS role_count FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID LIKE 'RES_WF_TRF_%' GROUP BY RESOURCE_ID ORDER BY RESOURCE_ID;
