-- 2026-06-17 通讯录导入/导出/模板端点登记 PT_RESOURCE，授权同「通讯录列表」(RES_PTL_ADDR_LIST) 的角色集。
-- 端点：GET /api/employees/template、POST /api/employees/import、GET /api/employees/export。
-- 幂等：先删后插。schema 变更走 SQL 直接执行（禁 Flyway）。

DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID IN ('RES_PTL_ADDR_TPL','RES_PTL_ADDR_IMPORT','RES_PTL_ADDR_EXPORT');
DELETE FROM PT_RESOURCE      WHERE RESOURCE_ID IN ('RES_PTL_ADDR_TPL','RES_PTL_ADDR_IMPORT','RES_PTL_ADDR_EXPORT');

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'RES_PTL_ADDR_TPL','/api/employees/template','GET','通讯录导入模板',0,0,0,NULL,0,'PORTAL',NOW(),'seed',NOW(),'seed','2026-06-17 通讯录导入导出'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='RES_PTL_ADDR_TPL');
INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'RES_PTL_ADDR_IMPORT','/api/employees/import','POST','通讯录导入',0,0,0,NULL,0,'PORTAL',NOW(),'seed',NOW(),'seed','2026-06-17 通讯录导入导出'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='RES_PTL_ADDR_IMPORT');
INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
     MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
SELECT 'RES_PTL_ADDR_EXPORT','/api/employees/export','GET','通讯录导出',0,0,0,NULL,0,'PORTAL',NOW(),'seed',NOW(),'seed','2026-06-17 通讯录导入导出'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID='RES_PTL_ADDR_EXPORT');

-- 授权：复制 RES_PTL_ADDR_LIST 的角色集给 3 个新资源
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT UPPER(SUBSTRING(REPLACE(UUID(),'-',''),1,32)), s.ROLE_ID, m.RID, s.SYS_CODE, NOW()
FROM (SELECT ROLE_ID, SYS_CODE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='RES_PTL_ADDR_LIST') s
CROSS JOIN (SELECT 'RES_PTL_ADDR_TPL' RID UNION ALL SELECT 'RES_PTL_ADDR_IMPORT' UNION ALL SELECT 'RES_PTL_ADDR_EXPORT') m;
