-- 动态查询「客户维度」对象搜索接口登记：/api/reports/customers/search (GET)
-- 镜像已有的 R_RPT_EMP_SEARCH（员工搜索），并绑定到与之相同的所有角色。
-- 幂等：已存在则跳过。

-- 1) 注册资源（拷贝 R_RPT_EMP_SEARCH 的 ISMENU/PARENT/STATUS/SYS_CODE 等属性）
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME,
                         ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER)
SELECT 'R_RPT_CUST_SEARCH', '/api/reports/customers/search', 'GET', '动态查询客户搜索',
       ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, NOW(), 'system'
FROM PT_RESOURCE
WHERE RESOURCE_ID = 'R_RPT_EMP_SEARCH'
  AND NOT EXISTS (SELECT 1 FROM (SELECT RESOURCE_ID FROM PT_RESOURCE) x
                  WHERE x.RESOURCE_ID = 'R_RPT_CUST_SEARCH');

-- 2) 绑定到与员工搜索相同的全部角色
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT CONCAT('RR_CUST_', rr.ROLE_ID), rr.ROLE_ID, 'R_RPT_CUST_SEARCH', rr.SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE rr
WHERE rr.RESOURCE_ID = 'R_RPT_EMP_SEARCH'
  AND NOT EXISTS (SELECT 1 FROM (SELECT ROLE_ID, RESOURCE_ID FROM PT_ROLE_RESOURCE) x
                  WHERE x.ROLE_ID = rr.ROLE_ID AND x.RESOURCE_ID = 'R_RPT_CUST_SEARCH');
