-- ============================================================
-- bootstrap 模块 IT 测试库初始化脚本
-- 创建日期：2026-04-28
-- 适用版本：FU-15 B 方案（用本地真 MySQL 替代 H2 测试，独立测试库不污染 onepl）
-- ============================================================
--
-- 背景：
--   bootstrap 模块 IT 测试此前用 H2 LEGACY/MYSQL 内存库，但 H2 与生产 MySQL 8.0 行为差异
--   多次踩坑（FU-9 user_notification 大小写、TINYINT(1) syntax 等）。FU-15 B 方案改用本地
--   真 MySQL 8.0 + 独立测试库 onepl_test_bootstrap，与 performance/report 模块统一架构。
--
-- 用法：
--   1) 第一次搭建本地开发环境时执行：
--      mysql -uroot -p123456 < docs/superpowers/sql/2026-04-28-onepl-test-bootstrap-init.sql
--      然后按下方"步骤 2"清单执行 8 个 DDL + 15 个 perf 迁移 + 8 个 report 迁移
--   2) 后续如需重置，先 mysqldump 备份到 docs/superpowers/sql/backup/，再 DROP DATABASE
--      onepl_test_bootstrap; 重新执行本脚本
--
-- ============================================================
-- 步骤 1：创建独立测试库
-- ============================================================

CREATE DATABASE IF NOT EXISTS onepl_test_bootstrap
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci
    COMMENT 'bootstrap 模块 IT 专用库（FU-15 B）';

-- ============================================================
-- 步骤 2：导入业务模块 DDL（8 个，无 FK 跨表约束，顺序无关）
-- ============================================================
--
-- bash:
--   for f in docs/schema/ddl-auth.sql docs/schema/ddl-governance.sql \
--            docs/schema/ddl-workflow.sql docs/schema/ddl-customer.sql \
--            docs/schema/ddl-portal.sql docs/schema/ddl-bizapp.sql \
--            docs/schema/ddl-performance.sql docs/schema/ddl-report.sql; do
--     mysql -uroot -p123456 --default-character-set=utf8mb4 onepl_test_bootstrap < "$f"
--   done
--
-- 完成后表数：58
--
-- ============================================================
-- 步骤 3：导入 performance 模块 V1.x.y 增量迁移脚本（15 个，按文件名顺序）
-- ============================================================
--
-- 这些迁移脚本含 V1.2 perf_export_task / V1.3 perf_run_task uk / V1.4 perf_target_owner 等
-- ALTER TABLE 增量，与生产 onepl 库 schema 状态对齐。
--
-- bash:
--   for f in $(ls performance-engine-center/src/main/resources/sql/V1_*.sql | sort); do
--     mysql -uroot -p123456 --default-character-set=utf8mb4 onepl_test_bootstrap < "$f"
--   done
--
-- 完成后表数：59（+1 perf_export_task）
--
-- ============================================================
-- 步骤 4：导入 report 模块 V1.0.x 增量迁移脚本（8 个，按文件名顺序）
-- ============================================================
--
-- bash:
--   for f in $(ls report-analytics-center/src/main/resources/sql/report/V1_*.sql | sort); do
--     mysql -uroot -p123456 --default-character-set=utf8mb4 onepl_test_bootstrap < "$f"
--   done
--
-- 完成后表数：59（report 增量主要是 PT_RESOURCE 数据 + rpt_export_task 已含在 ddl-report.sql）
--
-- ============================================================
-- 步骤 4bis：DDL 与生产代码字段对齐补齐
-- ============================================================
--
-- ddl-customer.sql 缺 touch_task.sla_warning 列（代码 TouchTask.java:50 / TouchTaskMapper.xml 用），
-- bootstrap CustomerMarketingCenterIT 切真 MySQL 后必须补齐：
--
-- ALTER TABLE touch_task
--   ADD COLUMN sla_warning TINYINT(1) DEFAULT 0
--   COMMENT 'SLA预警标记(代码契约字段，DDL补齐)';
--
-- 此为生产 DDL 偏差，本期跨任务范围不修 docs/schema/ddl-customer.sql 源文件，
-- 仅在 onepl_test_bootstrap 测试库中补齐让 IT 通过。
-- TODO（FU-X）：后续把 sla_warning 列补到 ddl-customer.sql + 提供 V1_x 迁移脚本。
--
-- ============================================================
-- 步骤 5：Flowable / Quartz 表（act_* / flw_* / qrtz_* 共 81 张）
-- ============================================================
--
-- 经实测，Flowable 7.0.1 在真 MySQL 8 + Druid 连接池组合下，首次启动时
-- `flowable.database-schema-update: true` 的 schemaUpdate 路径会因 ACT_GE_PROPERTY
-- 表读取异常进入死循环（schemaUpdate Flowable 内部需要 Property 数据兜底，但 Liquibase
-- 建表+插入元数据的事务边界与 Druid PreparedStatement 缓存冲突），导致 ApplicationContext
-- 启动失败。
--
-- 规避方案：从生产 onepl 库直接复制 act_* / flw_* / qrtz_* 共 81 张表的 schema + 元数据
-- （Liquibase databasechangelog + act_ge_property 13 行 schema.version 数据）到测试库，
-- Flowable 启动时直接走 schemaCheckVersion() 成功路径，无需走 schemaUpdate() 重建。
--
-- bash（首次搭建测试库时跑一次）：
--   # 5.1 导出表清单
--   mysql -uroot -p123456 onepl -e "SHOW TABLES LIKE 'act_%'" -B -N > /tmp/flowable_tables.txt
--   mysql -uroot -p123456 onepl -e "SHOW TABLES LIKE 'flw_%'" -B -N >> /tmp/flowable_tables.txt
--   mysql -uroot -p123456 onepl -e "SHOW TABLES LIKE 'qrtz_%'" -B -N >> /tmp/flowable_tables.txt
--   tr -d '\r' < /tmp/flowable_tables.txt > /tmp/flowable_tables_lf.txt
--
--   # 5.2 导出 schema (DDL)，逐表防 word splitting
--   > /tmp/flowable_schema.sql
--   while read t; do
--     mysqldump -uroot -p123456 --no-data --skip-add-locks --skip-comments \
--       --skip-set-charset --no-create-db onepl "$t" 2>/dev/null >> /tmp/flowable_schema.sql
--   done < /tmp/flowable_tables_lf.txt
--
--   # 5.3 导出元数据 (Liquibase changelog + act_ge_property schema.version)
--   > /tmp/flowable_meta.sql
--   for t in act_ge_property act_app_databasechangelog act_app_databasechangeloglock \
--            act_cmmn_databasechangelog act_cmmn_databasechangeloglock \
--            act_dmn_databasechangelog act_dmn_databasechangeloglock \
--            flw_ev_databasechangelog flw_ev_databasechangeloglock; do
--     mysqldump -uroot -p123456 --no-create-info --skip-add-locks --skip-comments \
--       --skip-set-charset --no-create-db --skip-extended-insert onepl "$t" 2>/dev/null \
--       | grep -E "^(INSERT|/\*!40000)" >> /tmp/flowable_meta.sql
--   done
--
--   # 5.4 导入测试库
--   mysql -uroot -p123456 --default-character-set=utf8mb4 onepl_test_bootstrap < /tmp/flowable_schema.sql
--   mysql -uroot -p123456 --default-character-set=utf8mb4 onepl_test_bootstrap < /tmp/flowable_meta.sql
--
-- 验证：
--   mysql -uroot -p123456 onepl_test_bootstrap -e "SELECT COUNT(*) FROM act_ge_property;"
--   期望：13（schema.version 等 Flowable 元数据 13 行）
--   mysql -uroot -p123456 onepl_test_bootstrap -e "SELECT COUNT(*) FROM information_schema.tables
--     WHERE table_schema='onepl_test_bootstrap' AND (table_name LIKE 'act_%' OR table_name LIKE 'flw_%' OR table_name LIKE 'qrtz_%');"
--   期望：81
--
-- ============================================================
-- 验证
-- ============================================================
--
-- mysql -uroot -p123456 -e "SELECT COUNT(*) AS cnt FROM information_schema.tables WHERE
--   table_schema='onepl_test_bootstrap' AND table_name NOT LIKE 'act_%' AND table_name NOT
--   LIKE 'flw_%' AND table_name NOT LIKE 'qrtz_%';"
-- 期望输出：cnt = 59
--
-- ============================================================
-- 与 onepl_test_v103 / onepl 的关系
-- ============================================================
--
--   onepl                    生产/集成环境主库（performance 模块 IT 也用此库）
--   onepl_test_v103          report 模块 IT 专用库
--   onepl_test_bootstrap     bootstrap 模块 IT 专用库（本脚本）
--
-- 三库独立，避免相互污染。
