-- 客户标签真实 Excel 导入：模板下载 + 文件导入资源。
-- 新资源继承原 C_TAG_IMPORT 的角色授权，可重复执行。
START TRANSACTION;

INSERT INTO PT_RESOURCE
  (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL,
   MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE,
   CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK)
VALUES
  ('C_TAG_IMPORT_FILE', '/api/tags/*/customers/import-file', 'POST', '客户标签Excel导入', NULL,
   0, 0, '0', 'M_MKT_TAGS', 0, 'CUSTOMER', NOW(), 'customer-tag-excel-0811', NOW(), 'customer-tag-excel-0811', '追加或全量替换导入'),
  ('C_TAG_IMPORT_TMPL', '/api/tags/*/customers/import-template', 'GET', '下载客户标签导入模板', NULL,
   0, 0, '0', 'M_MKT_TAGS', 0, 'CUSTOMER', NOW(), 'customer-tag-excel-0811', NOW(), 'customer-tag-excel-0811', '按当前标签生成Excel模板')
ON DUPLICATE KEY UPDATE
  RESOURCE_URL = VALUES(RESOURCE_URL),
  RESOURCE_METHOD = VALUES(RESOURCE_METHOD),
  MENU_NAME = VALUES(MENU_NAME),
  PARENT_RESOURCE_ID = VALUES(PARENT_RESOURCE_ID),
  STATUS = 0,
  UPDATE_TIME = NOW(),
  UPDATE_USER = 'customer-tag-excel-0811';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT LOWER(MD5(CONCAT(ROLE_ID, ':C_TAG_IMPORT_FILE'))), ROLE_ID,
       'C_TAG_IMPORT_FILE', SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE
WHERE RESOURCE_ID = 'C_TAG_IMPORT';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT LOWER(MD5(CONCAT(ROLE_ID, ':C_TAG_IMPORT_TMPL'))), ROLE_ID,
       'C_TAG_IMPORT_TMPL', SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE
WHERE RESOURCE_ID = 'C_TAG_IMPORT';

COMMIT;
