-- 2026-06-17 信息聚合菜单：PT_RESOURCE 新增「信息聚合」分组 + 4 个叶子菜单，
-- 授权给与「数据导入」(M_PERF_IMPORT) 相同的角色集（谁能看数据导入，谁就能看信息聚合）。
-- 菜单来源于 my-menus（按角色过滤），故必须建节点 + 授权。schema 变更走 SQL 直接执行（禁 Flyway）。
-- 幂等：先删 M_GROUP_INFO / M_INFO_* 及其角色绑定再重建。

-- 1) 幂等清理
DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID IN ('M_GROUP_INFO','M_INFO_NAV','M_INFO_ADDR','M_INFO_PRODUCT','M_INFO_DOC');
DELETE FROM PT_RESOURCE      WHERE RESOURCE_ID IN ('M_GROUP_INFO','M_INFO_NAV','M_INFO_ADDR','M_INFO_PRODUCT','M_INFO_DOC');

-- 2) 根级分组顺序：工作台0 / 信息聚合1 / 绩效2 / 内部评价3 / 报表4 / 系统5（显式设值，幂等）
UPDATE PT_RESOURCE SET MENU_RANK_NO = 2 WHERE RESOURCE_ID = 'M_GROUP_PERF';
UPDATE PT_RESOURCE SET MENU_RANK_NO = 3 WHERE RESOURCE_ID = 'M_GROUP_EVAL';
UPDATE PT_RESOURCE SET MENU_RANK_NO = 4 WHERE RESOURCE_ID = 'M_GROUP_REPORT';
UPDATE PT_RESOURCE SET MENU_RANK_NO = 5 WHERE RESOURCE_ID = 'M_GROUP_SYSTEM';

-- 3) 分组节点（parent=NULL，endflag=0 非叶；URL 用 #group/ 占位避免唯一约束冲突）
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL, MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK) VALUES
('M_GROUP_INFO', '#group/info', 'MENU', '信息聚合', '📚', 1, 1, '0', NULL, 0, 'YITI', NOW(), 'seed', NOW(), NULL, '信息聚合菜单 2026-06-17');

-- 4) 叶子菜单（4 个，URL 对齐前端路由 /info/*）
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL, MENU_RANK_NO, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK) VALUES
('M_INFO_NAV',     '/info/nav',          'MENU', '网址导航',   NULL, 1, 1, '1', 'M_GROUP_INFO', 0, 'YITI', NOW(), 'seed', NOW(), NULL, '信息聚合菜单 2026-06-17'),
('M_INFO_ADDR',    '/info/address-book', 'MENU', '通讯录',     NULL, 2, 1, '1', 'M_GROUP_INFO', 0, 'YITI', NOW(), 'seed', NOW(), NULL, '信息聚合菜单 2026-06-17'),
('M_INFO_PRODUCT', '/info/products',     'MENU', '产品资料库', NULL, 3, 1, '1', 'M_GROUP_INFO', 0, 'YITI', NOW(), 'seed', NOW(), NULL, '信息聚合菜单 2026-06-17'),
('M_INFO_DOC',     '/info/documents',    'MENU', '常用文档',   NULL, 4, 1, '1', 'M_GROUP_INFO', 0, 'YITI', NOW(), 'seed', NOW(), NULL, '信息聚合菜单 2026-06-17');

-- 5) 授权：分组 + 4 叶子，按 M_PERF_IMPORT 的角色集复制（每个新菜单给同一批 role_id）
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT UPPER(SUBSTRING(REPLACE(UUID(),'-',''),1,32)), s.ROLE_ID, m.RID, s.SYS_CODE, NOW()
FROM (SELECT ROLE_ID, SYS_CODE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID='M_PERF_IMPORT') s
CROSS JOIN (SELECT 'M_GROUP_INFO' RID UNION ALL SELECT 'M_INFO_NAV' UNION ALL SELECT 'M_INFO_ADDR'
            UNION ALL SELECT 'M_INFO_PRODUCT' UNION ALL SELECT 'M_INFO_DOC') m;
