-- Fix PT_RESOURCE issues after alignment
-- Execute against onepl database

-- 1. Fix RES_CUSTOMER_EDIT: transfer role mappings and correct URL/method
INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_LEAD_EDIT' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_EDIT';
DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_EDIT';
DELETE FROM PT_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_EDIT';
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, ISMENU, SYS_CODE) VALUES
('RES_CUSTOMER_EDIT', '/api/customers/*/edit', 'POST', '编辑客户', 0, 'PLATFORM');

-- 2. Fix RES_LEAD_IMP_BATCH URL
DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUST_LD_IMP_BTCH';
DELETE FROM PT_RESOURCE WHERE RESOURCE_ID = 'RES_CUST_LD_IMP_BTCH';
UPDATE PT_RESOURCE SET RESOURCE_URL = '/api/leads/import/batches/*' WHERE RESOURCE_ID = 'RES_LEAD_IMP_BATCH';

-- 3. Fix RES_CUSTOMER_DEL_APP METHOD
UPDATE PT_RESOURCE SET RESOURCE_METHOD = 'POST' WHERE RESOURCE_ID = 'RES_CUSTOMER_DEL_APP';

-- 4. Delete redundant RES_CUST_POOL
DELETE FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUST_POOL';
DELETE FROM PT_RESOURCE WHERE RESOURCE_ID = 'RES_CUST_POOL';

-- 5. Add missing RES_PTL_PRD_EXPRT
INSERT IGNORE INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, ISMENU, SYS_CODE) VALUES
('RES_PTL_PRD_EXPRT', '/api/products/export', 'GET', '导出产品', 0, 'PLATFORM');

-- 6. Fix tag methods
UPDATE PT_RESOURCE SET RESOURCE_METHOD = 'PUT' WHERE RESOURCE_ID = 'RES_TAG_ENABLE';
UPDATE PT_RESOURCE SET RESOURCE_METHOD = 'PUT' WHERE RESOURCE_ID = 'RES_TAG_DISABLE';
UPDATE PT_RESOURCE SET RESOURCE_METHOD = 'GET' WHERE RESOURCE_ID = 'RES_TAG_EXPORT';

-- 7. Transfer role mappings for new entries
INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_PTL_WORKSPACE' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_PTL_SHRTCUT_PUT';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_PTL_PRD_EXPRT' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_PTL_PRD_SPT_AVL';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_CUST_EXPORT' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_LIST';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_LD_IMP_PRE' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_LEAD_IMPORT';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_LD_IMP_BATC' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_LEAD_IMP_BATCH';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_POOL_CLAIM' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CLAIM_CREATE';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_POOL_LIST' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_LIST';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_TRPT_SUM' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_LIST';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_TRPT_LST' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_LIST';

INSERT IGNORE INTO PT_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
SELECT ROLE_ID, 'RES_CUST_TRPT_EXP' FROM PT_ROLE_RESOURCE WHERE RESOURCE_ID = 'RES_CUSTOMER_LIST';
