START TRANSACTION;

INSERT INTO PT_RESOURCE
 (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
  MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_USER, REMARK)
SELECT 'P_YD_ACCT_IMP_TPL', '/api/yundun/accountability-violations/import-template', 'GET', '人员违规-导入模板下载',
       0, 0, '0', 'M_YD_ACCOUNTABILITY', 0, 'YD', 'system', '与人员违规导入权限保持一致'
WHERE NOT EXISTS (
    SELECT 1 FROM PT_RESOURCE
    WHERE RESOURCE_URL = '/api/yundun/accountability-violations/import-template'
      AND RESOURCE_METHOD = 'GET' AND SYS_CODE = 'YD'
);

INSERT INTO PT_RESOURCE
 (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_RANK_NO, ISMENU,
  MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE, CREATE_USER, REMARK)
SELECT 'P_YD_CREDIT_IMP_TPL', '/api/yundun/credit-violations/import-template', 'GET', '信贷风险-导入模板下载',
       0, 0, '0', 'M_YD_CREDIT', 0, 'YD', 'system', '与信贷风险导入权限保持一致'
WHERE NOT EXISTS (
    SELECT 1 FROM PT_RESOURCE
    WHERE RESOURCE_URL = '/api/yundun/credit-violations/import-template'
      AND RESOURCE_METHOD = 'GET' AND SYS_CODE = 'YD'
);

INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT SUBSTRING(MD5(CONCAT(source.ROLE_ID, '|P_YD_ACCT_IMP_TPL')), 1, 16),
       source.ROLE_ID, 'P_YD_ACCT_IMP_TPL', 'YD', NOW()
FROM PT_ROLE_RESOURCE source
WHERE source.RESOURCE_ID = 'P_YD_ACCT_IMPORT'
  AND NOT EXISTS (
      SELECT 1 FROM PT_ROLE_RESOURCE target
      WHERE target.ROLE_ID = source.ROLE_ID AND target.RESOURCE_ID = 'P_YD_ACCT_IMP_TPL'
  );

INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT SUBSTRING(MD5(CONCAT(source.ROLE_ID, '|P_YD_CREDIT_IMP_TPL')), 1, 16),
       source.ROLE_ID, 'P_YD_CREDIT_IMP_TPL', 'YD', NOW()
FROM PT_ROLE_RESOURCE source
WHERE source.RESOURCE_ID = 'P_YD_CREDIT_IMPORT'
  AND NOT EXISTS (
      SELECT 1 FROM PT_ROLE_RESOURCE target
      WHERE target.ROLE_ID = source.ROLE_ID AND target.RESOURCE_ID = 'P_YD_CREDIT_IMP_TPL'
  );

COMMIT;
