-- 2026-06-12 数据导入源文件归档到 OBS：PERF_IMPORT_BATCH 增列 SOURCE_OBJECT_KEY（FileApi fileId）
-- Flyway 已禁用，DDL 由开发/DBA 直接在目标库执行。
ALTER TABLE PERF_IMPORT_BATCH
    ADD COLUMN SOURCE_OBJECT_KEY VARCHAR(64) NULL COMMENT '导入源文件归档到 OBS 的 fileId';
