-- 大屏范围管理菜单登记（MySQL 8.0，可直接执行、可幂等复跑）。
-- 仅登记“机构经营画像”“命名机构组”两个前端菜单，并授权给 SYS_ADMIN；
-- 不包含预检、验收 SELECT、存储过程、DDL 或业务数据变更。

START TRANSACTION;

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL, MENU_RANK_NO,
     ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE,
     CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK) SELECT 'M_RPT_SCR_PROF', '/screen-admin/org-profiles', 'MENU', '机构经营画像', NULL, 9, 1, '1', 'M_GROUP_REPORT', 0, 'YITI',
       NOW(), '2026-08-13-screen-menu', NOW(), '2026-08-13-screen-menu', '大屏机构经营画像管理菜单'
 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID = 'M_RPT_SCR_PROF');

UPDATE PT_RESOURCE
   SET RESOURCE_URL = '/screen-admin/org-profiles', RESOURCE_METHOD = 'MENU', MENU_NAME = '机构经营画像',
       MENU_ICON_URL = NULL, MENU_RANK_NO = 9, ISMENU = 1, MENU_ENDFLAG = '1',
       PARENT_RESOURCE_ID = 'M_GROUP_REPORT', STATUS = 0, SYS_CODE = 'YITI',
       UPDATE_USER = '2026-08-13-screen-menu', REMARK = '大屏机构经营画像管理菜单'
 WHERE RESOURCE_ID = 'M_RPT_SCR_PROF';

INSERT INTO PT_RESOURCE
    (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, MENU_ICON_URL, MENU_RANK_NO,
     ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, STATUS, SYS_CODE,
     CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER, REMARK) SELECT 'M_RPT_SCR_GRP', '/screen-admin/org-groups', 'MENU', '命名机构组', NULL, 10, 1, '1', 'M_GROUP_REPORT', 0, 'YITI',
       NOW(), '2026-08-13-screen-menu', NOW(), '2026-08-13-screen-menu', '大屏命名机构组管理菜单'
 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PT_RESOURCE WHERE RESOURCE_ID = 'M_RPT_SCR_GRP');

UPDATE PT_RESOURCE
   SET RESOURCE_URL = '/screen-admin/org-groups', RESOURCE_METHOD = 'MENU', MENU_NAME = '命名机构组',
       MENU_ICON_URL = NULL, MENU_RANK_NO = 10, ISMENU = 1, MENU_ENDFLAG = '1',
       PARENT_RESOURCE_ID = 'M_GROUP_REPORT', STATUS = 0, SYS_CODE = 'YITI',
       UPDATE_USER = '2026-08-13-screen-menu', REMARK = '大屏命名机构组管理菜单'
 WHERE RESOURCE_ID = 'M_RPT_SCR_GRP';

INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME) SELECT 'SCRM_ORG_PROF_SYS_ADMIN', ROLE_ID, 'M_RPT_SCR_PROF', 'PLATFORM', NOW()
  FROM PT_ROLE
 WHERE ROLE_CODE = 'SYS_ADMIN'
   AND RECORD_STATUS = 0
   AND NOT EXISTS (SELECT 1 FROM PT_ROLE_RESOURCE WHERE ID = 'SCRM_ORG_PROF_SYS_ADMIN');

UPDATE PT_ROLE_RESOURCE target_grant
  JOIN PT_ROLE sys_admin ON sys_admin.ROLE_CODE = 'SYS_ADMIN' AND sys_admin.RECORD_STATUS = 0
   SET target_grant.ROLE_ID = sys_admin.ROLE_ID,
       target_grant.RESOURCE_ID = 'M_RPT_SCR_PROF',
       target_grant.SYS_CODE = 'PLATFORM'
 WHERE target_grant.ID = 'SCRM_ORG_PROF_SYS_ADMIN';

INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME) SELECT 'SCRM_ORG_GRP_SYS_ADMIN', ROLE_ID, 'M_RPT_SCR_GRP', 'PLATFORM', NOW()
  FROM PT_ROLE
 WHERE ROLE_CODE = 'SYS_ADMIN'
   AND RECORD_STATUS = 0
   AND NOT EXISTS (SELECT 1 FROM PT_ROLE_RESOURCE WHERE ID = 'SCRM_ORG_GRP_SYS_ADMIN');

UPDATE PT_ROLE_RESOURCE target_grant
  JOIN PT_ROLE sys_admin ON sys_admin.ROLE_CODE = 'SYS_ADMIN' AND sys_admin.RECORD_STATUS = 0
   SET target_grant.ROLE_ID = sys_admin.ROLE_ID,
       target_grant.RESOURCE_ID = 'M_RPT_SCR_GRP',
       target_grant.SYS_CODE = 'PLATFORM'
 WHERE target_grant.ID = 'SCRM_ORG_GRP_SYS_ADMIN';

COMMIT;
