-- ============================================================================
-- 历史数据查询新增两个查询页的资源登记 + 角色绑定
--   数据导入查询  菜单 M_HIST_DTIMPORT  /guarantee/data-import
--   公告查询      菜单 M_HIST_NOTICE    /guarantee/notice
-- 接口（report 模块，只读，SYS_CODE=RPT）：
--   R_RPT_DTIMP_LIST  GET /api/reports/data-imports
--   R_RPT_DTIMP_DATA  GET /api/reports/data-imports/*
--   R_RPT_NOTICE_LIST GET /api/reports/notices
--   R_RPT_NOTICE_DET  GET /api/reports/notices/*
-- 角色绑定：与同组「担保查询」(M_GUARANTEE_QUERY) 同一批角色（保持一致可见性）。
-- 幂等：已存在则跳过。
-- ============================================================================

-- 1) 菜单资源（挂在 M_GROUP_GUARANTEE 历史数据查询 组下，沿用 担保查询 的属性）
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, MENU_RANK_NO, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER)
SELECT * FROM (
  SELECT 'M_HIST_DTIMPORT' RESOURCE_ID, '/guarantee/data-import' RESOURCE_URL, 'MENU' RESOURCE_METHOD, '数据导入查询' MENU_NAME, 1 ISMENU, '1' MENU_ENDFLAG, 'M_GROUP_GUARANTEE' PARENT_RESOURCE_ID, 2 MENU_RANK_NO, 0 STATUS, 'YITI' SYS_CODE, NOW() CREATE_TIME, 'system' CREATE_USER
  UNION ALL
  SELECT 'M_HIST_NOTICE', '/guarantee/notice', 'MENU', '公告查询', 1, '1', 'M_GROUP_GUARANTEE', 3, 0, 'YITI', NOW(), 'system'
) t
WHERE NOT EXISTS (SELECT 1 FROM (SELECT RESOURCE_ID FROM PT_RESOURCE) x WHERE x.RESOURCE_ID = t.RESOURCE_ID);

-- 2) 接口资源（report 只读，PARENT 为 NULL，SYS_CODE=RPT）
INSERT INTO PT_RESOURCE (RESOURCE_ID, RESOURCE_URL, RESOURCE_METHOD, MENU_NAME, ISMENU, MENU_ENDFLAG, PARENT_RESOURCE_ID, MENU_RANK_NO, STATUS, SYS_CODE, CREATE_TIME, CREATE_USER)
SELECT * FROM (
  SELECT 'R_RPT_DTIMP_LIST' RESOURCE_ID, '/api/reports/data-imports' RESOURCE_URL, 'GET' RESOURCE_METHOD, '数据导入查询-列表' MENU_NAME, 0 ISMENU, '0' MENU_ENDFLAG, CAST(NULL AS CHAR) PARENT_RESOURCE_ID, 0 MENU_RANK_NO, 0 STATUS, 'RPT' SYS_CODE, NOW() CREATE_TIME, 'system' CREATE_USER
  UNION ALL SELECT 'R_RPT_DTIMP_DATA', '/api/reports/data-imports/*', 'GET', '数据导入查询-透视数据', 0, '0', NULL, 0, 0, 'RPT', NOW(), 'system'
  UNION ALL SELECT 'R_RPT_NOTICE_LIST', '/api/reports/notices', 'GET', '公告查询-列表', 0, '0', NULL, 0, 0, 'RPT', NOW(), 'system'
  UNION ALL SELECT 'R_RPT_NOTICE_DET', '/api/reports/notices/*', 'GET', '公告查询-详情', 0, '0', NULL, 0, 0, 'RPT', NOW(), 'system'
) t
WHERE NOT EXISTS (SELECT 1 FROM (SELECT RESOURCE_ID FROM PT_RESOURCE) x WHERE x.RESOURCE_ID = t.RESOURCE_ID);

-- 3) 角色绑定：凡是有「担保查询」(M_GUARANTEE_QUERY) 的角色，都绑定这 6 个新资源
INSERT INTO PT_ROLE_RESOURCE (ID, ROLE_ID, RESOURCE_ID, SYS_CODE, CREATE_TIME)
SELECT SUBSTRING(MD5(CONCAT(rr.ROLE_ID,'|',n.RESOURCE_ID)),1,16), rr.ROLE_ID, n.RESOURCE_ID, rr.SYS_CODE, NOW()
FROM PT_ROLE_RESOURCE rr
CROSS JOIN (
  SELECT 'M_HIST_DTIMPORT' RESOURCE_ID UNION ALL SELECT 'M_HIST_NOTICE'
  UNION ALL SELECT 'R_RPT_DTIMP_LIST' UNION ALL SELECT 'R_RPT_DTIMP_DATA'
  UNION ALL SELECT 'R_RPT_NOTICE_LIST' UNION ALL SELECT 'R_RPT_NOTICE_DET'
) n
WHERE rr.RESOURCE_ID = 'M_GUARANTEE_QUERY'
  AND NOT EXISTS (SELECT 1 FROM (SELECT ROLE_ID, RESOURCE_ID FROM PT_ROLE_RESOURCE) x
                  WHERE x.ROLE_ID = rr.ROLE_ID AND x.RESOURCE_ID = n.RESOURCE_ID);
