-- ============================================================
-- RedEngineSmokeIT：无角色切换的多用户/多角色 RBAC 测试夹具
--
-- 约束：
--   1. 三个临时用户都复用 admin 的 BCrypt 密码摘要，测试密码固定为 password；
--   2. RE_IT_REPORT 仅有报送员，RE_IT_BRREV 仅有支部审核员；
--   3. RE_IT_UNION 同时有报送员和支部审核员，且故意将支部审核员标成默认角色，
--      用于证明授权必须取全部有效角色并集，而不是只取 DEFAULT_ASSIGN 角色；
--   4. 固定 USER_ID/USERNAME 若已被非本夹具数据占用，利用临时表主键冲突立即失败，禁止接管；
--   5. 不登记、不调用 A_SWITCH_ROLE；所有写入由配套 cleanup 按所有权标记精确清理。
-- ============================================================

-- PT_USER.USER_ID/USERNAME 没有完整的业务唯一约束，固定夹具必须先验证所有权。
-- unsafe 行存在时第二次插入 GUARD_ID=1 会触发主键冲突，使 @Sql 在任何业务写入前 fail-close。
DROP TEMPORARY TABLE IF EXISTS TMP_RE_IT_FIXTURE_OWNERSHIP_GUARD;
CREATE TEMPORARY TABLE TMP_RE_IT_FIXTURE_OWNERSHIP_GUARD (GUARD_ID INT PRIMARY KEY);
INSERT INTO TMP_RE_IT_FIXTURE_OWNERSHIP_GUARD (GUARD_ID) VALUES (1);
INSERT INTO TMP_RE_IT_FIXTURE_OWNERSHIP_GUARD (GUARD_ID)
SELECT 1
WHERE EXISTS (
    SELECT 1
      FROM PT_USER
     WHERE (USER_ID IN ('RE_IT_REPORT', 'RE_IT_BRREV', 'RE_IT_UNION')
            OR USERNAME IN ('re_it_report', 're_it_brrev', 're_it_union'))
       AND NOT (
           CREATE_AUTHOR = 'RedEngineSmokeIT'
           AND REMARK = 'RedEngineSmokeIT managed fixture 2026-08-10'
           AND ((USER_ID = 'RE_IT_REPORT' AND USERNAME = 're_it_report')
             OR (USER_ID = 'RE_IT_BRREV' AND USERNAME = 're_it_brrev')
             OR (USER_ID = 'RE_IT_UNION' AND USERNAME = 're_it_union'))
       )
);
DROP TEMPORARY TABLE TMP_RE_IT_FIXTURE_OWNERSHIP_GUARD;

INSERT INTO PT_USER
    (USER_ID, USERNAME, USERCHNNAME, PWD, ISENABLED, ISLOCKED, PASS_WRONG_COUNT, CREATE_AUTHOR, REMARK)
SELECT 'RE_IT_REPORT', 're_it_report', '红色引擎IT-仅报送', PWD, 0, 0, 0,
       'RedEngineSmokeIT', 'RedEngineSmokeIT managed fixture 2026-08-10'
FROM PT_USER
WHERE USERNAME = 'admin'
  AND NOT EXISTS (SELECT 1 FROM PT_USER WHERE USER_ID = 'RE_IT_REPORT');

INSERT INTO PT_USER
    (USER_ID, USERNAME, USERCHNNAME, PWD, ISENABLED, ISLOCKED, PASS_WRONG_COUNT, CREATE_AUTHOR, REMARK)
SELECT 'RE_IT_BRREV', 're_it_brrev', '红色引擎IT-仅支部审核', PWD, 0, 0, 0,
       'RedEngineSmokeIT', 'RedEngineSmokeIT managed fixture 2026-08-10'
FROM PT_USER
WHERE USERNAME = 'admin'
  AND NOT EXISTS (SELECT 1 FROM PT_USER WHERE USER_ID = 'RE_IT_BRREV');

INSERT INTO PT_USER
    (USER_ID, USERNAME, USERCHNNAME, PWD, ISENABLED, ISLOCKED, PASS_WRONG_COUNT, CREATE_AUTHOR, REMARK)
SELECT 'RE_IT_UNION', 're_it_union', '红色引擎IT-报送审核并集', PWD, 0, 0, 0,
       'RedEngineSmokeIT', 'RedEngineSmokeIT managed fixture 2026-08-10'
FROM PT_USER
WHERE USERNAME = 'admin'
  AND NOT EXISTS (SELECT 1 FROM PT_USER WHERE USER_ID = 'RE_IT_UNION');

INSERT INTO PT_USER_ROLE (USER_ID, ROLE_ID, DEFAULT_ASSIGN, INHERIT_ASSIGN, GROUP_ASSING)
SELECT 'RE_IT_REPORT', 'RE_ROLE_4', 1, 0, 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_USER_ROLE WHERE USER_ID = 'RE_IT_REPORT' AND ROLE_ID = 'RE_ROLE_4'
);

INSERT INTO PT_USER_ROLE (USER_ID, ROLE_ID, DEFAULT_ASSIGN, INHERIT_ASSIGN, GROUP_ASSING)
SELECT 'RE_IT_BRREV', 'RE_ROLE_2', 1, 0, 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_USER_ROLE WHERE USER_ID = 'RE_IT_BRREV' AND ROLE_ID = 'RE_ROLE_2'
);

INSERT INTO PT_USER_ROLE (USER_ID, ROLE_ID, DEFAULT_ASSIGN, INHERIT_ASSIGN, GROUP_ASSING)
SELECT 'RE_IT_UNION', 'RE_ROLE_2', 1, 0, 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_USER_ROLE WHERE USER_ID = 'RE_IT_UNION' AND ROLE_ID = 'RE_ROLE_2'
);

INSERT INTO PT_USER_ROLE (USER_ID, ROLE_ID, DEFAULT_ASSIGN, INHERIT_ASSIGN, GROUP_ASSING)
SELECT 'RE_IT_UNION', 'RE_ROLE_4', 0, 0, 0
WHERE NOT EXISTS (
    SELECT 1 FROM PT_USER_ROLE WHERE USER_ID = 'RE_IT_UNION' AND ROLE_ID = 'RE_ROLE_4'
);

-- 上报接口必须从登录工号解析党组织；party_role 只是兼容描述，不参与 RBAC。
INSERT INTO RE_USER_PARTY_MAP (USER_ID, PARTY_ORG_ID, PARTY_ROLE, DELETED)
SELECT 'RE_IT_REPORT', MIN(ID), 'REPORTER', 0
FROM RE_PARTY_ORG
WHERE DELETED = 0
  AND NOT EXISTS (SELECT 1 FROM RE_USER_PARTY_MAP WHERE USER_ID = 'RE_IT_REPORT')
HAVING MIN(ID) IS NOT NULL;

INSERT INTO RE_USER_PARTY_MAP (USER_ID, PARTY_ORG_ID, PARTY_ROLE, DELETED)
SELECT 'RE_IT_UNION', MIN(ID), 'REPORTER', 0
FROM RE_PARTY_ORG
WHERE DELETED = 0
  AND NOT EXISTS (SELECT 1 FROM RE_USER_PARTY_MAP WHERE USER_ID = 'RE_IT_UNION')
HAVING MIN(ID) IS NOT NULL;
