-- ============================================================
-- H2 Schema for Auth Tables (auth-permission-center)
-- Based on create-table.sql DDL, converted for H2 compatibility
-- MODE=MYSQL enables MySQL-compatible syntax
-- ============================================================

-- 用户表
CREATE TABLE IF NOT EXISTS PT_USER (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(200) NOT NULL,
    USERCHNNAME VARCHAR(200) NOT NULL,
    PWD VARCHAR(64) DEFAULT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    USER_TYPE VARCHAR(8) DEFAULT '1',
    ISEXPIRED INT DEFAULT 0,
    ISLOCKED INT DEFAULT 0,
    PASS_WRONG_COUNT INT DEFAULT 0,
    ISENABLED INT DEFAULT 1,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_AUTHOR VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AUTHOR VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL,
    PWD_UPDATE_TIME DATETIME DEFAULT NULL
);

-- 角色表
CREATE TABLE IF NOT EXISTS PT_ROLE (
    ROLE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ROLE_CODE VARCHAR(50) NOT NULL,
    ROLE_CHNAME VARCHAR(100) NOT NULL,
    RECORD_STATUS INT DEFAULT 0,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

-- 资源表
CREATE TABLE IF NOT EXISTS PT_RESOURCE (
    RESOURCE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    RESOURCE_URL VARCHAR(256) NOT NULL,
    RESOURCE_METHOD VARCHAR(10) NOT NULL,
    MENU_NAME VARCHAR(256) NOT NULL,
    MENU_ICON_URL VARCHAR(256) DEFAULT NULL,
    MENU_RANK_NO INT DEFAULT 0,
    ISMENU INT DEFAULT 0,
    MENU_ENDFLAG VARCHAR(10) DEFAULT '0',
    PARENT_RESOURCE_ID VARCHAR(60) DEFAULT NULL,
    STATUS INT DEFAULT 0,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

-- 用户角色关联表（联合主键）
CREATE TABLE IF NOT EXISTS PT_USER_ROLE (
    USER_ID VARCHAR(50) NOT NULL,
    ROLE_ID VARCHAR(50) NOT NULL,
    DEFAULT_ASSIGN INT DEFAULT 0,
    INHERIT_ASSIGN INT DEFAULT 0,
    GROUP_ASSING INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- 角色资源关联表
CREATE TABLE IF NOT EXISTS PT_ROLE_RESOURCE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_ID VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(20) NOT NULL,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 角色业务范围表
CREATE TABLE IF NOT EXISTS PT_ROLE_BIZ_SCOPE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_ID VARCHAR(50) NOT NULL,
    BIZ_TYPE VARCHAR(50) NOT NULL,
    DATA_SCOPE VARCHAR(50) NOT NULL,
    RECORD_STATUS INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

-- 机构表
CREATE TABLE IF NOT EXISTS EXT_ORG_INFO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORG_CODE VARCHAR(20) NOT NULL UNIQUE,
    ORG_NAME VARCHAR(200) NOT NULL,
    ORG_LEVEL INT DEFAULT NULL,
    P_ID VARCHAR(20) DEFAULT NULL,
    DEPT_NO VARCHAR(50) DEFAULT NULL,
    ORGAN_STATE INT DEFAULT 0,
    ADM_DIVISION_CODE VARCHAR(20) DEFAULT NULL,
    ADM_DIVISION_NAME VARCHAR(255) DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL
);

-- 用户机构关联表（联合主键）
CREATE TABLE IF NOT EXISTS EXT_USER_ORG (
    USER_ID VARCHAR(50) NOT NULL,
    ORG_CODE VARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ORG_CODE)
);
