-- ============================================
-- 模块：绩效引擎中心 (performance-engine-center)
-- 描述：数据版本控制、指标定义、指标引用、KPI方案、目标方案、
--       绩效导入、任务执行、指标结果宽表、KPI结果、
--       客户业绩分配、分配调整、目标修正
-- 版本：V1
-- 创建日期：2026-03-25
-- ============================================

SET NAMES utf8mb4;

-- -------------------------------------------
-- 1. 数据版本控制表
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `SYS_CONTROL` (
  `id` varchar(32) NOT NULL COMMENT '控制ID',
  `scope_dim` varchar(20) NOT NULL COMMENT '维度：EMP/ORG/CUST',
  `latest_data_date` date NOT NULL COMMENT '最新数据日期',
  `current_version` varchar(32) DEFAULT NULL COMMENT '当前有效版本',
  `is_valid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_dim_date` (`scope_dim`, `latest_data_date`),
  KEY `idx_scope_valid` (`scope_dim`, `is_valid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='数据版本控制表';

-- -------------------------------------------
-- 2. 指标定义表
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_METRIC_DEF` (
  `id` varchar(32) NOT NULL COMMENT '指标ID',
  `metric_code` varchar(64) NOT NULL COMMENT '指标编码(唯一)',
  `metric_name` varchar(200) NOT NULL COMMENT '指标名称',
  `metric_name_en` varchar(200) DEFAULT NULL COMMENT '英文名',
  `metric_desc` text COMMENT '指标说明',
  `base_dim` varchar(20) NOT NULL COMMENT '基础维度：EMP/ORG/CUST',
  `metric_level` int(11) NOT NULL COMMENT '指标层级：1/2/3',
  `calc_freq` varchar(20) NOT NULL COMMENT '计算频率：DAY/MONTH/QUARTER/YEAR',
  `calc_mode` varchar(20) NOT NULL COMMENT '计算方式：AUTO/MANUAL',
  `calc_logic_type` varchar(50) DEFAULT NULL COMMENT '逻辑类型：SQL/PROC/EXPR/SUMMARY',
  `sql_text` longtext COMMENT '一级指标SQL/存储过程文本',
  `expr_text` text COMMENT '二/三级指标表达式',
  `summary_rule` varchar(20) DEFAULT NULL COMMENT '机构汇总规则：SUM/AVG等',
  `ref_metric_codes` text COMMENT '引用指标列表(JSON数组)',
  `val_slot` int(11) DEFAULT NULL COMMENT '宽表槽位(1..200)',
  `unit` varchar(16) DEFAULT NULL COMMENT '单位：元/万元/%',
  `decimal_places` tinyint DEFAULT '2' COMMENT '小数位数',
  `deleted` tinyint DEFAULT '0' COMMENT '0=存在 1=删除',
  `description` varchar(500) DEFAULT NULL COMMENT '指标详细描述（补充 metric_desc）',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/DISABLED',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_metric_code` (`metric_code`),
  UNIQUE KEY `uk_base_dim_slot_alive` ((IF(deleted=0, CONCAT(base_dim,'#',val_slot), NULL))),
  KEY `idx_dim_level` (`base_dim`, `metric_level`),
  KEY `idx_status` (`status`),
  KEY `idx_val_slot` (`val_slot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='指标定义表';

-- -------------------------------------------
-- 3. 指标引用关系
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_METRIC_REF` (
  `id` varchar(32) NOT NULL COMMENT '引用ID',
  `metric_code` varchar(64) NOT NULL COMMENT '引用者(上层指标)',
  `ref_metric_code` varchar(64) NOT NULL COMMENT '被引用(下层指标)',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_metric_ref` (`metric_code`, `ref_metric_code`),
  KEY `idx_ref_metric` (`ref_metric_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='指标引用关系';

-- -------------------------------------------
-- 4. KPI方案
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_KPI_SCHEME` (
  `id` varchar(32) NOT NULL COMMENT '方案ID',
  `scheme_code` varchar(64) NOT NULL COMMENT '方案编码(唯一)',
  `scheme_name` varchar(200) NOT NULL COMMENT '方案名称',
  `cycle_type` varchar(20) NOT NULL COMMENT '周期：MONTHLY/QUARTERLY',
  `open_detail` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否向员工开放明细',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/DISABLED',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheme_code` (`scheme_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='KPI方案';

-- -------------------------------------------
-- 5. KPI方案项
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_KPI_ITEM` (
  `id` varchar(32) NOT NULL COMMENT '项ID',
  `scheme_id` varchar(32) NOT NULL COMMENT '方案ID',
  `metric_code` varchar(64) NOT NULL COMMENT '指标编码(人员维度)',
  `weight` decimal(10,4) NOT NULL COMMENT '权重',
  `multiplier` decimal(10,4) NOT NULL DEFAULT 1 COMMENT '加倍系数',
  `min_score` decimal(10,4) NOT NULL DEFAULT 0 COMMENT '最低分',
  `max_score` decimal(10,4) NOT NULL DEFAULT 999999 COMMENT '最高分',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheme_metric` (`scheme_id`, `metric_code`),
  KEY `idx_scheme_id` (`scheme_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='KPI方案项';

-- -------------------------------------------
-- 6. 目标方案
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_TARGET_PLAN` (
  `id` varchar(32) NOT NULL COMMENT '目标方案ID',
  `plan_code` varchar(64) NOT NULL COMMENT '方案编码(唯一)',
  `plan_name` varchar(200) NOT NULL COMMENT '方案名称',
  `kpi_scheme_id` varchar(32) NOT NULL COMMENT '关联KPI方案ID',
  `target_dim` varchar(20) NOT NULL COMMENT '目标维度：EMP/ORG',
  `target_cycle` varchar(20) NOT NULL COMMENT '目标周期：YEAR/QUARTER',
  `effective_date` date NOT NULL COMMENT '生效日期',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/DISABLED',
  `owner_emp_id` varchar(32) DEFAULT NULL COMMENT '归属员工（SELF/SELF_ASSIGNED scope 列）',
  `owner_org_code` varchar(50) DEFAULT NULL COMMENT '归属机构（ORG/ORG_SUBTREE scope 列）',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_code` (`plan_code`),
  KEY `idx_status` (`status`),
  KEY `idx_owner_emp` (`owner_emp_id`),
  KEY `idx_owner_org` (`owner_org_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='目标方案';

-- -------------------------------------------
-- 7. 目标值/基础值
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_TARGET_VALUE` (
  `id` varchar(32) NOT NULL COMMENT '目标值ID',
  `plan_id` varchar(32) NOT NULL COMMENT '目标方案ID',
  `subject_type` varchar(20) NOT NULL COMMENT '对象类型：EMP/ORG',
  `subject_id` varchar(50) NOT NULL COMMENT '对象ID(emp_id/org_code)',
  `cycle_key` varchar(20) NOT NULL COMMENT '周期键：2026或2026Q1',
  `metric_code` varchar(64) NOT NULL COMMENT '指标编码',
  `target_value` decimal(20,4) NOT NULL COMMENT '目标值',
  `base_value` decimal(20,4) DEFAULT NULL COMMENT '基础值(可空，默认为0)',
  `owner_emp_id` varchar(32) DEFAULT NULL COMMENT '归属员工（SELF/SELF_ASSIGNED scope 列）',
  `owner_org_code` varchar(50) DEFAULT NULL COMMENT '归属机构（ORG/ORG_SUBTREE scope 列）',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_subject_cycle_metric` (`plan_id`, `subject_type`, `subject_id`, `cycle_key`, `metric_code`),
  KEY `idx_metric_code` (`metric_code`),
  KEY `idx_subject` (`subject_type`, `subject_id`, `cycle_key`),
  KEY `idx_owner_emp` (`owner_emp_id`),
  KEY `idx_owner_org` (`owner_org_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='目标值/基础值';

-- -------------------------------------------
-- 8. 绩效导入批次
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_IMPORT_BATCH` (
  `id` varchar(32) NOT NULL COMMENT '批次ID',
  `batch_no` varchar(64) NOT NULL COMMENT '批次号',
  `import_type` varchar(20) NOT NULL COMMENT '导入类型：INDEX_RESULT/KPI_RESULT/TARGET',
  `dim` varchar(20) NOT NULL COMMENT '维度：EMP/ORG/CUST',
  `as_of_date` date DEFAULT NULL COMMENT 'KPI导入基准日(可空)',
  `file_name` varchar(255) DEFAULT NULL COMMENT '文件名',
  `file_md5` varchar(64) DEFAULT NULL COMMENT '文件MD5',
  `status` varchar(20) NOT NULL DEFAULT 'CREATED' COMMENT '状态：CREATED/SUCCESS/FAILED',
  `total_rows` int(11) NOT NULL DEFAULT 0 COMMENT '总行数',
  `success_rows` int(11) NOT NULL DEFAULT 0 COMMENT '成功行数',
  `error_rows` int(11) NOT NULL DEFAULT 0 COMMENT '失败行数',
  `error_file_object_id` varchar(32) DEFAULT NULL COMMENT '错误明细文件ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_by` varchar(32) NOT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_no` (`batch_no`),
  KEY `idx_status` (`status`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='绩效导入批次';

-- -------------------------------------------
-- 9. 绩效任务执行日志
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_RUN_TASK` (
  `id` varchar(32) NOT NULL COMMENT '任务ID',
  `task_type` varchar(30) NOT NULL COMMENT '类型：METRIC_TRIAL/METRIC_RUN/KPI_RUN/RECALC',
  `task_key` varchar(100) DEFAULT NULL COMMENT '关键键(如metric_code)',
  `data_date` date DEFAULT NULL COMMENT '数据日期',
  `data_version` varchar(32) DEFAULT NULL COMMENT '数据版本',
  `params_json` longtext COMMENT '参数(JSON)',
  `status` varchar(20) NOT NULL DEFAULT 'RUNNING' COMMENT '状态：RUNNING/SUCCESS/FAILED',
  `started_by` varchar(32) NOT NULL COMMENT '发起人',
  `start_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `error_msg` longtext COMMENT '错误信息',
  `result_preview_json` longtext COMMENT '结果预览(JSON)',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_task_type` (`task_type`),
  KEY `idx_status` (`status`),
  KEY `idx_started_by` (`started_by`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='绩效任务执行日志';

-- -------------------------------------------
-- 10. 员工指标结果宽表 (val_1 ~ val_200)
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `EMP_INDEX_RESULT` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `data_date` date NOT NULL COMMENT '数据日期',
  `version` varchar(32) NOT NULL COMMENT '数据版本',
  `emp_id` varchar(50) NOT NULL COMMENT '员工工号',
  `val_1` decimal(20,4) DEFAULT NULL COMMENT 'val_1',
  `val_2` decimal(20,4) DEFAULT NULL COMMENT 'val_2',
  `val_3` decimal(20,4) DEFAULT NULL COMMENT 'val_3',
  `val_4` decimal(20,4) DEFAULT NULL COMMENT 'val_4',
  `val_5` decimal(20,4) DEFAULT NULL COMMENT 'val_5',
  `val_6` decimal(20,4) DEFAULT NULL COMMENT 'val_6',
  `val_7` decimal(20,4) DEFAULT NULL COMMENT 'val_7',
  `val_8` decimal(20,4) DEFAULT NULL COMMENT 'val_8',
  `val_9` decimal(20,4) DEFAULT NULL COMMENT 'val_9',
  `val_10` decimal(20,4) DEFAULT NULL COMMENT 'val_10',
  `val_11` decimal(20,4) DEFAULT NULL COMMENT 'val_11',
  `val_12` decimal(20,4) DEFAULT NULL COMMENT 'val_12',
  `val_13` decimal(20,4) DEFAULT NULL COMMENT 'val_13',
  `val_14` decimal(20,4) DEFAULT NULL COMMENT 'val_14',
  `val_15` decimal(20,4) DEFAULT NULL COMMENT 'val_15',
  `val_16` decimal(20,4) DEFAULT NULL COMMENT 'val_16',
  `val_17` decimal(20,4) DEFAULT NULL COMMENT 'val_17',
  `val_18` decimal(20,4) DEFAULT NULL COMMENT 'val_18',
  `val_19` decimal(20,4) DEFAULT NULL COMMENT 'val_19',
  `val_20` decimal(20,4) DEFAULT NULL COMMENT 'val_20',
  `val_21` decimal(20,4) DEFAULT NULL COMMENT 'val_21',
  `val_22` decimal(20,4) DEFAULT NULL COMMENT 'val_22',
  `val_23` decimal(20,4) DEFAULT NULL COMMENT 'val_23',
  `val_24` decimal(20,4) DEFAULT NULL COMMENT 'val_24',
  `val_25` decimal(20,4) DEFAULT NULL COMMENT 'val_25',
  `val_26` decimal(20,4) DEFAULT NULL COMMENT 'val_26',
  `val_27` decimal(20,4) DEFAULT NULL COMMENT 'val_27',
  `val_28` decimal(20,4) DEFAULT NULL COMMENT 'val_28',
  `val_29` decimal(20,4) DEFAULT NULL COMMENT 'val_29',
  `val_30` decimal(20,4) DEFAULT NULL COMMENT 'val_30',
  `val_31` decimal(20,4) DEFAULT NULL COMMENT 'val_31',
  `val_32` decimal(20,4) DEFAULT NULL COMMENT 'val_32',
  `val_33` decimal(20,4) DEFAULT NULL COMMENT 'val_33',
  `val_34` decimal(20,4) DEFAULT NULL COMMENT 'val_34',
  `val_35` decimal(20,4) DEFAULT NULL COMMENT 'val_35',
  `val_36` decimal(20,4) DEFAULT NULL COMMENT 'val_36',
  `val_37` decimal(20,4) DEFAULT NULL COMMENT 'val_37',
  `val_38` decimal(20,4) DEFAULT NULL COMMENT 'val_38',
  `val_39` decimal(20,4) DEFAULT NULL COMMENT 'val_39',
  `val_40` decimal(20,4) DEFAULT NULL COMMENT 'val_40',
  `val_41` decimal(20,4) DEFAULT NULL COMMENT 'val_41',
  `val_42` decimal(20,4) DEFAULT NULL COMMENT 'val_42',
  `val_43` decimal(20,4) DEFAULT NULL COMMENT 'val_43',
  `val_44` decimal(20,4) DEFAULT NULL COMMENT 'val_44',
  `val_45` decimal(20,4) DEFAULT NULL COMMENT 'val_45',
  `val_46` decimal(20,4) DEFAULT NULL COMMENT 'val_46',
  `val_47` decimal(20,4) DEFAULT NULL COMMENT 'val_47',
  `val_48` decimal(20,4) DEFAULT NULL COMMENT 'val_48',
  `val_49` decimal(20,4) DEFAULT NULL COMMENT 'val_49',
  `val_50` decimal(20,4) DEFAULT NULL COMMENT 'val_50',
  `val_51` decimal(20,4) DEFAULT NULL COMMENT 'val_51',
  `val_52` decimal(20,4) DEFAULT NULL COMMENT 'val_52',
  `val_53` decimal(20,4) DEFAULT NULL COMMENT 'val_53',
  `val_54` decimal(20,4) DEFAULT NULL COMMENT 'val_54',
  `val_55` decimal(20,4) DEFAULT NULL COMMENT 'val_55',
  `val_56` decimal(20,4) DEFAULT NULL COMMENT 'val_56',
  `val_57` decimal(20,4) DEFAULT NULL COMMENT 'val_57',
  `val_58` decimal(20,4) DEFAULT NULL COMMENT 'val_58',
  `val_59` decimal(20,4) DEFAULT NULL COMMENT 'val_59',
  `val_60` decimal(20,4) DEFAULT NULL COMMENT 'val_60',
  `val_61` decimal(20,4) DEFAULT NULL COMMENT 'val_61',
  `val_62` decimal(20,4) DEFAULT NULL COMMENT 'val_62',
  `val_63` decimal(20,4) DEFAULT NULL COMMENT 'val_63',
  `val_64` decimal(20,4) DEFAULT NULL COMMENT 'val_64',
  `val_65` decimal(20,4) DEFAULT NULL COMMENT 'val_65',
  `val_66` decimal(20,4) DEFAULT NULL COMMENT 'val_66',
  `val_67` decimal(20,4) DEFAULT NULL COMMENT 'val_67',
  `val_68` decimal(20,4) DEFAULT NULL COMMENT 'val_68',
  `val_69` decimal(20,4) DEFAULT NULL COMMENT 'val_69',
  `val_70` decimal(20,4) DEFAULT NULL COMMENT 'val_70',
  `val_71` decimal(20,4) DEFAULT NULL COMMENT 'val_71',
  `val_72` decimal(20,4) DEFAULT NULL COMMENT 'val_72',
  `val_73` decimal(20,4) DEFAULT NULL COMMENT 'val_73',
  `val_74` decimal(20,4) DEFAULT NULL COMMENT 'val_74',
  `val_75` decimal(20,4) DEFAULT NULL COMMENT 'val_75',
  `val_76` decimal(20,4) DEFAULT NULL COMMENT 'val_76',
  `val_77` decimal(20,4) DEFAULT NULL COMMENT 'val_77',
  `val_78` decimal(20,4) DEFAULT NULL COMMENT 'val_78',
  `val_79` decimal(20,4) DEFAULT NULL COMMENT 'val_79',
  `val_80` decimal(20,4) DEFAULT NULL COMMENT 'val_80',
  `val_81` decimal(20,4) DEFAULT NULL COMMENT 'val_81',
  `val_82` decimal(20,4) DEFAULT NULL COMMENT 'val_82',
  `val_83` decimal(20,4) DEFAULT NULL COMMENT 'val_83',
  `val_84` decimal(20,4) DEFAULT NULL COMMENT 'val_84',
  `val_85` decimal(20,4) DEFAULT NULL COMMENT 'val_85',
  `val_86` decimal(20,4) DEFAULT NULL COMMENT 'val_86',
  `val_87` decimal(20,4) DEFAULT NULL COMMENT 'val_87',
  `val_88` decimal(20,4) DEFAULT NULL COMMENT 'val_88',
  `val_89` decimal(20,4) DEFAULT NULL COMMENT 'val_89',
  `val_90` decimal(20,4) DEFAULT NULL COMMENT 'val_90',
  `val_91` decimal(20,4) DEFAULT NULL COMMENT 'val_91',
  `val_92` decimal(20,4) DEFAULT NULL COMMENT 'val_92',
  `val_93` decimal(20,4) DEFAULT NULL COMMENT 'val_93',
  `val_94` decimal(20,4) DEFAULT NULL COMMENT 'val_94',
  `val_95` decimal(20,4) DEFAULT NULL COMMENT 'val_95',
  `val_96` decimal(20,4) DEFAULT NULL COMMENT 'val_96',
  `val_97` decimal(20,4) DEFAULT NULL COMMENT 'val_97',
  `val_98` decimal(20,4) DEFAULT NULL COMMENT 'val_98',
  `val_99` decimal(20,4) DEFAULT NULL COMMENT 'val_99',
  `val_100` decimal(20,4) DEFAULT NULL COMMENT 'val_100',
  `val_101` decimal(20,4) DEFAULT NULL COMMENT 'val_101',
  `val_102` decimal(20,4) DEFAULT NULL COMMENT 'val_102',
  `val_103` decimal(20,4) DEFAULT NULL COMMENT 'val_103',
  `val_104` decimal(20,4) DEFAULT NULL COMMENT 'val_104',
  `val_105` decimal(20,4) DEFAULT NULL COMMENT 'val_105',
  `val_106` decimal(20,4) DEFAULT NULL COMMENT 'val_106',
  `val_107` decimal(20,4) DEFAULT NULL COMMENT 'val_107',
  `val_108` decimal(20,4) DEFAULT NULL COMMENT 'val_108',
  `val_109` decimal(20,4) DEFAULT NULL COMMENT 'val_109',
  `val_110` decimal(20,4) DEFAULT NULL COMMENT 'val_110',
  `val_111` decimal(20,4) DEFAULT NULL COMMENT 'val_111',
  `val_112` decimal(20,4) DEFAULT NULL COMMENT 'val_112',
  `val_113` decimal(20,4) DEFAULT NULL COMMENT 'val_113',
  `val_114` decimal(20,4) DEFAULT NULL COMMENT 'val_114',
  `val_115` decimal(20,4) DEFAULT NULL COMMENT 'val_115',
  `val_116` decimal(20,4) DEFAULT NULL COMMENT 'val_116',
  `val_117` decimal(20,4) DEFAULT NULL COMMENT 'val_117',
  `val_118` decimal(20,4) DEFAULT NULL COMMENT 'val_118',
  `val_119` decimal(20,4) DEFAULT NULL COMMENT 'val_119',
  `val_120` decimal(20,4) DEFAULT NULL COMMENT 'val_120',
  `val_121` decimal(20,4) DEFAULT NULL COMMENT 'val_121',
  `val_122` decimal(20,4) DEFAULT NULL COMMENT 'val_122',
  `val_123` decimal(20,4) DEFAULT NULL COMMENT 'val_123',
  `val_124` decimal(20,4) DEFAULT NULL COMMENT 'val_124',
  `val_125` decimal(20,4) DEFAULT NULL COMMENT 'val_125',
  `val_126` decimal(20,4) DEFAULT NULL COMMENT 'val_126',
  `val_127` decimal(20,4) DEFAULT NULL COMMENT 'val_127',
  `val_128` decimal(20,4) DEFAULT NULL COMMENT 'val_128',
  `val_129` decimal(20,4) DEFAULT NULL COMMENT 'val_129',
  `val_130` decimal(20,4) DEFAULT NULL COMMENT 'val_130',
  `val_131` decimal(20,4) DEFAULT NULL COMMENT 'val_131',
  `val_132` decimal(20,4) DEFAULT NULL COMMENT 'val_132',
  `val_133` decimal(20,4) DEFAULT NULL COMMENT 'val_133',
  `val_134` decimal(20,4) DEFAULT NULL COMMENT 'val_134',
  `val_135` decimal(20,4) DEFAULT NULL COMMENT 'val_135',
  `val_136` decimal(20,4) DEFAULT NULL COMMENT 'val_136',
  `val_137` decimal(20,4) DEFAULT NULL COMMENT 'val_137',
  `val_138` decimal(20,4) DEFAULT NULL COMMENT 'val_138',
  `val_139` decimal(20,4) DEFAULT NULL COMMENT 'val_139',
  `val_140` decimal(20,4) DEFAULT NULL COMMENT 'val_140',
  `val_141` decimal(20,4) DEFAULT NULL COMMENT 'val_141',
  `val_142` decimal(20,4) DEFAULT NULL COMMENT 'val_142',
  `val_143` decimal(20,4) DEFAULT NULL COMMENT 'val_143',
  `val_144` decimal(20,4) DEFAULT NULL COMMENT 'val_144',
  `val_145` decimal(20,4) DEFAULT NULL COMMENT 'val_145',
  `val_146` decimal(20,4) DEFAULT NULL COMMENT 'val_146',
  `val_147` decimal(20,4) DEFAULT NULL COMMENT 'val_147',
  `val_148` decimal(20,4) DEFAULT NULL COMMENT 'val_148',
  `val_149` decimal(20,4) DEFAULT NULL COMMENT 'val_149',
  `val_150` decimal(20,4) DEFAULT NULL COMMENT 'val_150',
  `val_151` decimal(20,4) DEFAULT NULL COMMENT 'val_151',
  `val_152` decimal(20,4) DEFAULT NULL COMMENT 'val_152',
  `val_153` decimal(20,4) DEFAULT NULL COMMENT 'val_153',
  `val_154` decimal(20,4) DEFAULT NULL COMMENT 'val_154',
  `val_155` decimal(20,4) DEFAULT NULL COMMENT 'val_155',
  `val_156` decimal(20,4) DEFAULT NULL COMMENT 'val_156',
  `val_157` decimal(20,4) DEFAULT NULL COMMENT 'val_157',
  `val_158` decimal(20,4) DEFAULT NULL COMMENT 'val_158',
  `val_159` decimal(20,4) DEFAULT NULL COMMENT 'val_159',
  `val_160` decimal(20,4) DEFAULT NULL COMMENT 'val_160',
  `val_161` decimal(20,4) DEFAULT NULL COMMENT 'val_161',
  `val_162` decimal(20,4) DEFAULT NULL COMMENT 'val_162',
  `val_163` decimal(20,4) DEFAULT NULL COMMENT 'val_163',
  `val_164` decimal(20,4) DEFAULT NULL COMMENT 'val_164',
  `val_165` decimal(20,4) DEFAULT NULL COMMENT 'val_165',
  `val_166` decimal(20,4) DEFAULT NULL COMMENT 'val_166',
  `val_167` decimal(20,4) DEFAULT NULL COMMENT 'val_167',
  `val_168` decimal(20,4) DEFAULT NULL COMMENT 'val_168',
  `val_169` decimal(20,4) DEFAULT NULL COMMENT 'val_169',
  `val_170` decimal(20,4) DEFAULT NULL COMMENT 'val_170',
  `val_171` decimal(20,4) DEFAULT NULL COMMENT 'val_171',
  `val_172` decimal(20,4) DEFAULT NULL COMMENT 'val_172',
  `val_173` decimal(20,4) DEFAULT NULL COMMENT 'val_173',
  `val_174` decimal(20,4) DEFAULT NULL COMMENT 'val_174',
  `val_175` decimal(20,4) DEFAULT NULL COMMENT 'val_175',
  `val_176` decimal(20,4) DEFAULT NULL COMMENT 'val_176',
  `val_177` decimal(20,4) DEFAULT NULL COMMENT 'val_177',
  `val_178` decimal(20,4) DEFAULT NULL COMMENT 'val_178',
  `val_179` decimal(20,4) DEFAULT NULL COMMENT 'val_179',
  `val_180` decimal(20,4) DEFAULT NULL COMMENT 'val_180',
  `val_181` decimal(20,4) DEFAULT NULL COMMENT 'val_181',
  `val_182` decimal(20,4) DEFAULT NULL COMMENT 'val_182',
  `val_183` decimal(20,4) DEFAULT NULL COMMENT 'val_183',
  `val_184` decimal(20,4) DEFAULT NULL COMMENT 'val_184',
  `val_185` decimal(20,4) DEFAULT NULL COMMENT 'val_185',
  `val_186` decimal(20,4) DEFAULT NULL COMMENT 'val_186',
  `val_187` decimal(20,4) DEFAULT NULL COMMENT 'val_187',
  `val_188` decimal(20,4) DEFAULT NULL COMMENT 'val_188',
  `val_189` decimal(20,4) DEFAULT NULL COMMENT 'val_189',
  `val_190` decimal(20,4) DEFAULT NULL COMMENT 'val_190',
  `val_191` decimal(20,4) DEFAULT NULL COMMENT 'val_191',
  `val_192` decimal(20,4) DEFAULT NULL COMMENT 'val_192',
  `val_193` decimal(20,4) DEFAULT NULL COMMENT 'val_193',
  `val_194` decimal(20,4) DEFAULT NULL COMMENT 'val_194',
  `val_195` decimal(20,4) DEFAULT NULL COMMENT 'val_195',
  `val_196` decimal(20,4) DEFAULT NULL COMMENT 'val_196',
  `val_197` decimal(20,4) DEFAULT NULL COMMENT 'val_197',
  `val_198` decimal(20,4) DEFAULT NULL COMMENT 'val_198',
  `val_199` decimal(20,4) DEFAULT NULL COMMENT 'val_199',
  `val_200` decimal(20,4) DEFAULT NULL COMMENT 'val_200',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_subject_date_ver` (`emp_id`, `data_date`, `version`),
  KEY `idx_date_ver` (`data_date`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='员工指标结果宽表';

-- -------------------------------------------
-- 11. 机构指标结果宽表 (val_1 ~ val_200)
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `ORG_INDEX_RESULT` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `data_date` date NOT NULL COMMENT '数据日期',
  `version` varchar(32) NOT NULL COMMENT '数据版本',
  `org_code` varchar(50) NOT NULL COMMENT '机构编码',
  `val_1` decimal(20,4) DEFAULT NULL COMMENT 'val_1',
  `val_2` decimal(20,4) DEFAULT NULL COMMENT 'val_2',
  `val_3` decimal(20,4) DEFAULT NULL COMMENT 'val_3',
  `val_4` decimal(20,4) DEFAULT NULL COMMENT 'val_4',
  `val_5` decimal(20,4) DEFAULT NULL COMMENT 'val_5',
  `val_6` decimal(20,4) DEFAULT NULL COMMENT 'val_6',
  `val_7` decimal(20,4) DEFAULT NULL COMMENT 'val_7',
  `val_8` decimal(20,4) DEFAULT NULL COMMENT 'val_8',
  `val_9` decimal(20,4) DEFAULT NULL COMMENT 'val_9',
  `val_10` decimal(20,4) DEFAULT NULL COMMENT 'val_10',
  `val_11` decimal(20,4) DEFAULT NULL COMMENT 'val_11',
  `val_12` decimal(20,4) DEFAULT NULL COMMENT 'val_12',
  `val_13` decimal(20,4) DEFAULT NULL COMMENT 'val_13',
  `val_14` decimal(20,4) DEFAULT NULL COMMENT 'val_14',
  `val_15` decimal(20,4) DEFAULT NULL COMMENT 'val_15',
  `val_16` decimal(20,4) DEFAULT NULL COMMENT 'val_16',
  `val_17` decimal(20,4) DEFAULT NULL COMMENT 'val_17',
  `val_18` decimal(20,4) DEFAULT NULL COMMENT 'val_18',
  `val_19` decimal(20,4) DEFAULT NULL COMMENT 'val_19',
  `val_20` decimal(20,4) DEFAULT NULL COMMENT 'val_20',
  `val_21` decimal(20,4) DEFAULT NULL COMMENT 'val_21',
  `val_22` decimal(20,4) DEFAULT NULL COMMENT 'val_22',
  `val_23` decimal(20,4) DEFAULT NULL COMMENT 'val_23',
  `val_24` decimal(20,4) DEFAULT NULL COMMENT 'val_24',
  `val_25` decimal(20,4) DEFAULT NULL COMMENT 'val_25',
  `val_26` decimal(20,4) DEFAULT NULL COMMENT 'val_26',
  `val_27` decimal(20,4) DEFAULT NULL COMMENT 'val_27',
  `val_28` decimal(20,4) DEFAULT NULL COMMENT 'val_28',
  `val_29` decimal(20,4) DEFAULT NULL COMMENT 'val_29',
  `val_30` decimal(20,4) DEFAULT NULL COMMENT 'val_30',
  `val_31` decimal(20,4) DEFAULT NULL COMMENT 'val_31',
  `val_32` decimal(20,4) DEFAULT NULL COMMENT 'val_32',
  `val_33` decimal(20,4) DEFAULT NULL COMMENT 'val_33',
  `val_34` decimal(20,4) DEFAULT NULL COMMENT 'val_34',
  `val_35` decimal(20,4) DEFAULT NULL COMMENT 'val_35',
  `val_36` decimal(20,4) DEFAULT NULL COMMENT 'val_36',
  `val_37` decimal(20,4) DEFAULT NULL COMMENT 'val_37',
  `val_38` decimal(20,4) DEFAULT NULL COMMENT 'val_38',
  `val_39` decimal(20,4) DEFAULT NULL COMMENT 'val_39',
  `val_40` decimal(20,4) DEFAULT NULL COMMENT 'val_40',
  `val_41` decimal(20,4) DEFAULT NULL COMMENT 'val_41',
  `val_42` decimal(20,4) DEFAULT NULL COMMENT 'val_42',
  `val_43` decimal(20,4) DEFAULT NULL COMMENT 'val_43',
  `val_44` decimal(20,4) DEFAULT NULL COMMENT 'val_44',
  `val_45` decimal(20,4) DEFAULT NULL COMMENT 'val_45',
  `val_46` decimal(20,4) DEFAULT NULL COMMENT 'val_46',
  `val_47` decimal(20,4) DEFAULT NULL COMMENT 'val_47',
  `val_48` decimal(20,4) DEFAULT NULL COMMENT 'val_48',
  `val_49` decimal(20,4) DEFAULT NULL COMMENT 'val_49',
  `val_50` decimal(20,4) DEFAULT NULL COMMENT 'val_50',
  `val_51` decimal(20,4) DEFAULT NULL COMMENT 'val_51',
  `val_52` decimal(20,4) DEFAULT NULL COMMENT 'val_52',
  `val_53` decimal(20,4) DEFAULT NULL COMMENT 'val_53',
  `val_54` decimal(20,4) DEFAULT NULL COMMENT 'val_54',
  `val_55` decimal(20,4) DEFAULT NULL COMMENT 'val_55',
  `val_56` decimal(20,4) DEFAULT NULL COMMENT 'val_56',
  `val_57` decimal(20,4) DEFAULT NULL COMMENT 'val_57',
  `val_58` decimal(20,4) DEFAULT NULL COMMENT 'val_58',
  `val_59` decimal(20,4) DEFAULT NULL COMMENT 'val_59',
  `val_60` decimal(20,4) DEFAULT NULL COMMENT 'val_60',
  `val_61` decimal(20,4) DEFAULT NULL COMMENT 'val_61',
  `val_62` decimal(20,4) DEFAULT NULL COMMENT 'val_62',
  `val_63` decimal(20,4) DEFAULT NULL COMMENT 'val_63',
  `val_64` decimal(20,4) DEFAULT NULL COMMENT 'val_64',
  `val_65` decimal(20,4) DEFAULT NULL COMMENT 'val_65',
  `val_66` decimal(20,4) DEFAULT NULL COMMENT 'val_66',
  `val_67` decimal(20,4) DEFAULT NULL COMMENT 'val_67',
  `val_68` decimal(20,4) DEFAULT NULL COMMENT 'val_68',
  `val_69` decimal(20,4) DEFAULT NULL COMMENT 'val_69',
  `val_70` decimal(20,4) DEFAULT NULL COMMENT 'val_70',
  `val_71` decimal(20,4) DEFAULT NULL COMMENT 'val_71',
  `val_72` decimal(20,4) DEFAULT NULL COMMENT 'val_72',
  `val_73` decimal(20,4) DEFAULT NULL COMMENT 'val_73',
  `val_74` decimal(20,4) DEFAULT NULL COMMENT 'val_74',
  `val_75` decimal(20,4) DEFAULT NULL COMMENT 'val_75',
  `val_76` decimal(20,4) DEFAULT NULL COMMENT 'val_76',
  `val_77` decimal(20,4) DEFAULT NULL COMMENT 'val_77',
  `val_78` decimal(20,4) DEFAULT NULL COMMENT 'val_78',
  `val_79` decimal(20,4) DEFAULT NULL COMMENT 'val_79',
  `val_80` decimal(20,4) DEFAULT NULL COMMENT 'val_80',
  `val_81` decimal(20,4) DEFAULT NULL COMMENT 'val_81',
  `val_82` decimal(20,4) DEFAULT NULL COMMENT 'val_82',
  `val_83` decimal(20,4) DEFAULT NULL COMMENT 'val_83',
  `val_84` decimal(20,4) DEFAULT NULL COMMENT 'val_84',
  `val_85` decimal(20,4) DEFAULT NULL COMMENT 'val_85',
  `val_86` decimal(20,4) DEFAULT NULL COMMENT 'val_86',
  `val_87` decimal(20,4) DEFAULT NULL COMMENT 'val_87',
  `val_88` decimal(20,4) DEFAULT NULL COMMENT 'val_88',
  `val_89` decimal(20,4) DEFAULT NULL COMMENT 'val_89',
  `val_90` decimal(20,4) DEFAULT NULL COMMENT 'val_90',
  `val_91` decimal(20,4) DEFAULT NULL COMMENT 'val_91',
  `val_92` decimal(20,4) DEFAULT NULL COMMENT 'val_92',
  `val_93` decimal(20,4) DEFAULT NULL COMMENT 'val_93',
  `val_94` decimal(20,4) DEFAULT NULL COMMENT 'val_94',
  `val_95` decimal(20,4) DEFAULT NULL COMMENT 'val_95',
  `val_96` decimal(20,4) DEFAULT NULL COMMENT 'val_96',
  `val_97` decimal(20,4) DEFAULT NULL COMMENT 'val_97',
  `val_98` decimal(20,4) DEFAULT NULL COMMENT 'val_98',
  `val_99` decimal(20,4) DEFAULT NULL COMMENT 'val_99',
  `val_100` decimal(20,4) DEFAULT NULL COMMENT 'val_100',
  `val_101` decimal(20,4) DEFAULT NULL COMMENT 'val_101',
  `val_102` decimal(20,4) DEFAULT NULL COMMENT 'val_102',
  `val_103` decimal(20,4) DEFAULT NULL COMMENT 'val_103',
  `val_104` decimal(20,4) DEFAULT NULL COMMENT 'val_104',
  `val_105` decimal(20,4) DEFAULT NULL COMMENT 'val_105',
  `val_106` decimal(20,4) DEFAULT NULL COMMENT 'val_106',
  `val_107` decimal(20,4) DEFAULT NULL COMMENT 'val_107',
  `val_108` decimal(20,4) DEFAULT NULL COMMENT 'val_108',
  `val_109` decimal(20,4) DEFAULT NULL COMMENT 'val_109',
  `val_110` decimal(20,4) DEFAULT NULL COMMENT 'val_110',
  `val_111` decimal(20,4) DEFAULT NULL COMMENT 'val_111',
  `val_112` decimal(20,4) DEFAULT NULL COMMENT 'val_112',
  `val_113` decimal(20,4) DEFAULT NULL COMMENT 'val_113',
  `val_114` decimal(20,4) DEFAULT NULL COMMENT 'val_114',
  `val_115` decimal(20,4) DEFAULT NULL COMMENT 'val_115',
  `val_116` decimal(20,4) DEFAULT NULL COMMENT 'val_116',
  `val_117` decimal(20,4) DEFAULT NULL COMMENT 'val_117',
  `val_118` decimal(20,4) DEFAULT NULL COMMENT 'val_118',
  `val_119` decimal(20,4) DEFAULT NULL COMMENT 'val_119',
  `val_120` decimal(20,4) DEFAULT NULL COMMENT 'val_120',
  `val_121` decimal(20,4) DEFAULT NULL COMMENT 'val_121',
  `val_122` decimal(20,4) DEFAULT NULL COMMENT 'val_122',
  `val_123` decimal(20,4) DEFAULT NULL COMMENT 'val_123',
  `val_124` decimal(20,4) DEFAULT NULL COMMENT 'val_124',
  `val_125` decimal(20,4) DEFAULT NULL COMMENT 'val_125',
  `val_126` decimal(20,4) DEFAULT NULL COMMENT 'val_126',
  `val_127` decimal(20,4) DEFAULT NULL COMMENT 'val_127',
  `val_128` decimal(20,4) DEFAULT NULL COMMENT 'val_128',
  `val_129` decimal(20,4) DEFAULT NULL COMMENT 'val_129',
  `val_130` decimal(20,4) DEFAULT NULL COMMENT 'val_130',
  `val_131` decimal(20,4) DEFAULT NULL COMMENT 'val_131',
  `val_132` decimal(20,4) DEFAULT NULL COMMENT 'val_132',
  `val_133` decimal(20,4) DEFAULT NULL COMMENT 'val_133',
  `val_134` decimal(20,4) DEFAULT NULL COMMENT 'val_134',
  `val_135` decimal(20,4) DEFAULT NULL COMMENT 'val_135',
  `val_136` decimal(20,4) DEFAULT NULL COMMENT 'val_136',
  `val_137` decimal(20,4) DEFAULT NULL COMMENT 'val_137',
  `val_138` decimal(20,4) DEFAULT NULL COMMENT 'val_138',
  `val_139` decimal(20,4) DEFAULT NULL COMMENT 'val_139',
  `val_140` decimal(20,4) DEFAULT NULL COMMENT 'val_140',
  `val_141` decimal(20,4) DEFAULT NULL COMMENT 'val_141',
  `val_142` decimal(20,4) DEFAULT NULL COMMENT 'val_142',
  `val_143` decimal(20,4) DEFAULT NULL COMMENT 'val_143',
  `val_144` decimal(20,4) DEFAULT NULL COMMENT 'val_144',
  `val_145` decimal(20,4) DEFAULT NULL COMMENT 'val_145',
  `val_146` decimal(20,4) DEFAULT NULL COMMENT 'val_146',
  `val_147` decimal(20,4) DEFAULT NULL COMMENT 'val_147',
  `val_148` decimal(20,4) DEFAULT NULL COMMENT 'val_148',
  `val_149` decimal(20,4) DEFAULT NULL COMMENT 'val_149',
  `val_150` decimal(20,4) DEFAULT NULL COMMENT 'val_150',
  `val_151` decimal(20,4) DEFAULT NULL COMMENT 'val_151',
  `val_152` decimal(20,4) DEFAULT NULL COMMENT 'val_152',
  `val_153` decimal(20,4) DEFAULT NULL COMMENT 'val_153',
  `val_154` decimal(20,4) DEFAULT NULL COMMENT 'val_154',
  `val_155` decimal(20,4) DEFAULT NULL COMMENT 'val_155',
  `val_156` decimal(20,4) DEFAULT NULL COMMENT 'val_156',
  `val_157` decimal(20,4) DEFAULT NULL COMMENT 'val_157',
  `val_158` decimal(20,4) DEFAULT NULL COMMENT 'val_158',
  `val_159` decimal(20,4) DEFAULT NULL COMMENT 'val_159',
  `val_160` decimal(20,4) DEFAULT NULL COMMENT 'val_160',
  `val_161` decimal(20,4) DEFAULT NULL COMMENT 'val_161',
  `val_162` decimal(20,4) DEFAULT NULL COMMENT 'val_162',
  `val_163` decimal(20,4) DEFAULT NULL COMMENT 'val_163',
  `val_164` decimal(20,4) DEFAULT NULL COMMENT 'val_164',
  `val_165` decimal(20,4) DEFAULT NULL COMMENT 'val_165',
  `val_166` decimal(20,4) DEFAULT NULL COMMENT 'val_166',
  `val_167` decimal(20,4) DEFAULT NULL COMMENT 'val_167',
  `val_168` decimal(20,4) DEFAULT NULL COMMENT 'val_168',
  `val_169` decimal(20,4) DEFAULT NULL COMMENT 'val_169',
  `val_170` decimal(20,4) DEFAULT NULL COMMENT 'val_170',
  `val_171` decimal(20,4) DEFAULT NULL COMMENT 'val_171',
  `val_172` decimal(20,4) DEFAULT NULL COMMENT 'val_172',
  `val_173` decimal(20,4) DEFAULT NULL COMMENT 'val_173',
  `val_174` decimal(20,4) DEFAULT NULL COMMENT 'val_174',
  `val_175` decimal(20,4) DEFAULT NULL COMMENT 'val_175',
  `val_176` decimal(20,4) DEFAULT NULL COMMENT 'val_176',
  `val_177` decimal(20,4) DEFAULT NULL COMMENT 'val_177',
  `val_178` decimal(20,4) DEFAULT NULL COMMENT 'val_178',
  `val_179` decimal(20,4) DEFAULT NULL COMMENT 'val_179',
  `val_180` decimal(20,4) DEFAULT NULL COMMENT 'val_180',
  `val_181` decimal(20,4) DEFAULT NULL COMMENT 'val_181',
  `val_182` decimal(20,4) DEFAULT NULL COMMENT 'val_182',
  `val_183` decimal(20,4) DEFAULT NULL COMMENT 'val_183',
  `val_184` decimal(20,4) DEFAULT NULL COMMENT 'val_184',
  `val_185` decimal(20,4) DEFAULT NULL COMMENT 'val_185',
  `val_186` decimal(20,4) DEFAULT NULL COMMENT 'val_186',
  `val_187` decimal(20,4) DEFAULT NULL COMMENT 'val_187',
  `val_188` decimal(20,4) DEFAULT NULL COMMENT 'val_188',
  `val_189` decimal(20,4) DEFAULT NULL COMMENT 'val_189',
  `val_190` decimal(20,4) DEFAULT NULL COMMENT 'val_190',
  `val_191` decimal(20,4) DEFAULT NULL COMMENT 'val_191',
  `val_192` decimal(20,4) DEFAULT NULL COMMENT 'val_192',
  `val_193` decimal(20,4) DEFAULT NULL COMMENT 'val_193',
  `val_194` decimal(20,4) DEFAULT NULL COMMENT 'val_194',
  `val_195` decimal(20,4) DEFAULT NULL COMMENT 'val_195',
  `val_196` decimal(20,4) DEFAULT NULL COMMENT 'val_196',
  `val_197` decimal(20,4) DEFAULT NULL COMMENT 'val_197',
  `val_198` decimal(20,4) DEFAULT NULL COMMENT 'val_198',
  `val_199` decimal(20,4) DEFAULT NULL COMMENT 'val_199',
  `val_200` decimal(20,4) DEFAULT NULL COMMENT 'val_200',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_subject_date_ver` (`org_code`, `data_date`, `version`),
  KEY `idx_date_ver` (`data_date`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='机构指标结果宽表';

-- -------------------------------------------
-- 12. 客户指标结果宽表 (val_1 ~ val_200)
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `CUST_INDEX_RESULT` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `data_date` date NOT NULL COMMENT '数据日期',
  `version` varchar(32) NOT NULL COMMENT '数据版本',
  `cust_id` varchar(50) NOT NULL COMMENT '客户ID',
  `val_1` decimal(20,4) DEFAULT NULL COMMENT 'val_1',
  `val_2` decimal(20,4) DEFAULT NULL COMMENT 'val_2',
  `val_3` decimal(20,4) DEFAULT NULL COMMENT 'val_3',
  `val_4` decimal(20,4) DEFAULT NULL COMMENT 'val_4',
  `val_5` decimal(20,4) DEFAULT NULL COMMENT 'val_5',
  `val_6` decimal(20,4) DEFAULT NULL COMMENT 'val_6',
  `val_7` decimal(20,4) DEFAULT NULL COMMENT 'val_7',
  `val_8` decimal(20,4) DEFAULT NULL COMMENT 'val_8',
  `val_9` decimal(20,4) DEFAULT NULL COMMENT 'val_9',
  `val_10` decimal(20,4) DEFAULT NULL COMMENT 'val_10',
  `val_11` decimal(20,4) DEFAULT NULL COMMENT 'val_11',
  `val_12` decimal(20,4) DEFAULT NULL COMMENT 'val_12',
  `val_13` decimal(20,4) DEFAULT NULL COMMENT 'val_13',
  `val_14` decimal(20,4) DEFAULT NULL COMMENT 'val_14',
  `val_15` decimal(20,4) DEFAULT NULL COMMENT 'val_15',
  `val_16` decimal(20,4) DEFAULT NULL COMMENT 'val_16',
  `val_17` decimal(20,4) DEFAULT NULL COMMENT 'val_17',
  `val_18` decimal(20,4) DEFAULT NULL COMMENT 'val_18',
  `val_19` decimal(20,4) DEFAULT NULL COMMENT 'val_19',
  `val_20` decimal(20,4) DEFAULT NULL COMMENT 'val_20',
  `val_21` decimal(20,4) DEFAULT NULL COMMENT 'val_21',
  `val_22` decimal(20,4) DEFAULT NULL COMMENT 'val_22',
  `val_23` decimal(20,4) DEFAULT NULL COMMENT 'val_23',
  `val_24` decimal(20,4) DEFAULT NULL COMMENT 'val_24',
  `val_25` decimal(20,4) DEFAULT NULL COMMENT 'val_25',
  `val_26` decimal(20,4) DEFAULT NULL COMMENT 'val_26',
  `val_27` decimal(20,4) DEFAULT NULL COMMENT 'val_27',
  `val_28` decimal(20,4) DEFAULT NULL COMMENT 'val_28',
  `val_29` decimal(20,4) DEFAULT NULL COMMENT 'val_29',
  `val_30` decimal(20,4) DEFAULT NULL COMMENT 'val_30',
  `val_31` decimal(20,4) DEFAULT NULL COMMENT 'val_31',
  `val_32` decimal(20,4) DEFAULT NULL COMMENT 'val_32',
  `val_33` decimal(20,4) DEFAULT NULL COMMENT 'val_33',
  `val_34` decimal(20,4) DEFAULT NULL COMMENT 'val_34',
  `val_35` decimal(20,4) DEFAULT NULL COMMENT 'val_35',
  `val_36` decimal(20,4) DEFAULT NULL COMMENT 'val_36',
  `val_37` decimal(20,4) DEFAULT NULL COMMENT 'val_37',
  `val_38` decimal(20,4) DEFAULT NULL COMMENT 'val_38',
  `val_39` decimal(20,4) DEFAULT NULL COMMENT 'val_39',
  `val_40` decimal(20,4) DEFAULT NULL COMMENT 'val_40',
  `val_41` decimal(20,4) DEFAULT NULL COMMENT 'val_41',
  `val_42` decimal(20,4) DEFAULT NULL COMMENT 'val_42',
  `val_43` decimal(20,4) DEFAULT NULL COMMENT 'val_43',
  `val_44` decimal(20,4) DEFAULT NULL COMMENT 'val_44',
  `val_45` decimal(20,4) DEFAULT NULL COMMENT 'val_45',
  `val_46` decimal(20,4) DEFAULT NULL COMMENT 'val_46',
  `val_47` decimal(20,4) DEFAULT NULL COMMENT 'val_47',
  `val_48` decimal(20,4) DEFAULT NULL COMMENT 'val_48',
  `val_49` decimal(20,4) DEFAULT NULL COMMENT 'val_49',
  `val_50` decimal(20,4) DEFAULT NULL COMMENT 'val_50',
  `val_51` decimal(20,4) DEFAULT NULL COMMENT 'val_51',
  `val_52` decimal(20,4) DEFAULT NULL COMMENT 'val_52',
  `val_53` decimal(20,4) DEFAULT NULL COMMENT 'val_53',
  `val_54` decimal(20,4) DEFAULT NULL COMMENT 'val_54',
  `val_55` decimal(20,4) DEFAULT NULL COMMENT 'val_55',
  `val_56` decimal(20,4) DEFAULT NULL COMMENT 'val_56',
  `val_57` decimal(20,4) DEFAULT NULL COMMENT 'val_57',
  `val_58` decimal(20,4) DEFAULT NULL COMMENT 'val_58',
  `val_59` decimal(20,4) DEFAULT NULL COMMENT 'val_59',
  `val_60` decimal(20,4) DEFAULT NULL COMMENT 'val_60',
  `val_61` decimal(20,4) DEFAULT NULL COMMENT 'val_61',
  `val_62` decimal(20,4) DEFAULT NULL COMMENT 'val_62',
  `val_63` decimal(20,4) DEFAULT NULL COMMENT 'val_63',
  `val_64` decimal(20,4) DEFAULT NULL COMMENT 'val_64',
  `val_65` decimal(20,4) DEFAULT NULL COMMENT 'val_65',
  `val_66` decimal(20,4) DEFAULT NULL COMMENT 'val_66',
  `val_67` decimal(20,4) DEFAULT NULL COMMENT 'val_67',
  `val_68` decimal(20,4) DEFAULT NULL COMMENT 'val_68',
  `val_69` decimal(20,4) DEFAULT NULL COMMENT 'val_69',
  `val_70` decimal(20,4) DEFAULT NULL COMMENT 'val_70',
  `val_71` decimal(20,4) DEFAULT NULL COMMENT 'val_71',
  `val_72` decimal(20,4) DEFAULT NULL COMMENT 'val_72',
  `val_73` decimal(20,4) DEFAULT NULL COMMENT 'val_73',
  `val_74` decimal(20,4) DEFAULT NULL COMMENT 'val_74',
  `val_75` decimal(20,4) DEFAULT NULL COMMENT 'val_75',
  `val_76` decimal(20,4) DEFAULT NULL COMMENT 'val_76',
  `val_77` decimal(20,4) DEFAULT NULL COMMENT 'val_77',
  `val_78` decimal(20,4) DEFAULT NULL COMMENT 'val_78',
  `val_79` decimal(20,4) DEFAULT NULL COMMENT 'val_79',
  `val_80` decimal(20,4) DEFAULT NULL COMMENT 'val_80',
  `val_81` decimal(20,4) DEFAULT NULL COMMENT 'val_81',
  `val_82` decimal(20,4) DEFAULT NULL COMMENT 'val_82',
  `val_83` decimal(20,4) DEFAULT NULL COMMENT 'val_83',
  `val_84` decimal(20,4) DEFAULT NULL COMMENT 'val_84',
  `val_85` decimal(20,4) DEFAULT NULL COMMENT 'val_85',
  `val_86` decimal(20,4) DEFAULT NULL COMMENT 'val_86',
  `val_87` decimal(20,4) DEFAULT NULL COMMENT 'val_87',
  `val_88` decimal(20,4) DEFAULT NULL COMMENT 'val_88',
  `val_89` decimal(20,4) DEFAULT NULL COMMENT 'val_89',
  `val_90` decimal(20,4) DEFAULT NULL COMMENT 'val_90',
  `val_91` decimal(20,4) DEFAULT NULL COMMENT 'val_91',
  `val_92` decimal(20,4) DEFAULT NULL COMMENT 'val_92',
  `val_93` decimal(20,4) DEFAULT NULL COMMENT 'val_93',
  `val_94` decimal(20,4) DEFAULT NULL COMMENT 'val_94',
  `val_95` decimal(20,4) DEFAULT NULL COMMENT 'val_95',
  `val_96` decimal(20,4) DEFAULT NULL COMMENT 'val_96',
  `val_97` decimal(20,4) DEFAULT NULL COMMENT 'val_97',
  `val_98` decimal(20,4) DEFAULT NULL COMMENT 'val_98',
  `val_99` decimal(20,4) DEFAULT NULL COMMENT 'val_99',
  `val_100` decimal(20,4) DEFAULT NULL COMMENT 'val_100',
  `val_101` decimal(20,4) DEFAULT NULL COMMENT 'val_101',
  `val_102` decimal(20,4) DEFAULT NULL COMMENT 'val_102',
  `val_103` decimal(20,4) DEFAULT NULL COMMENT 'val_103',
  `val_104` decimal(20,4) DEFAULT NULL COMMENT 'val_104',
  `val_105` decimal(20,4) DEFAULT NULL COMMENT 'val_105',
  `val_106` decimal(20,4) DEFAULT NULL COMMENT 'val_106',
  `val_107` decimal(20,4) DEFAULT NULL COMMENT 'val_107',
  `val_108` decimal(20,4) DEFAULT NULL COMMENT 'val_108',
  `val_109` decimal(20,4) DEFAULT NULL COMMENT 'val_109',
  `val_110` decimal(20,4) DEFAULT NULL COMMENT 'val_110',
  `val_111` decimal(20,4) DEFAULT NULL COMMENT 'val_111',
  `val_112` decimal(20,4) DEFAULT NULL COMMENT 'val_112',
  `val_113` decimal(20,4) DEFAULT NULL COMMENT 'val_113',
  `val_114` decimal(20,4) DEFAULT NULL COMMENT 'val_114',
  `val_115` decimal(20,4) DEFAULT NULL COMMENT 'val_115',
  `val_116` decimal(20,4) DEFAULT NULL COMMENT 'val_116',
  `val_117` decimal(20,4) DEFAULT NULL COMMENT 'val_117',
  `val_118` decimal(20,4) DEFAULT NULL COMMENT 'val_118',
  `val_119` decimal(20,4) DEFAULT NULL COMMENT 'val_119',
  `val_120` decimal(20,4) DEFAULT NULL COMMENT 'val_120',
  `val_121` decimal(20,4) DEFAULT NULL COMMENT 'val_121',
  `val_122` decimal(20,4) DEFAULT NULL COMMENT 'val_122',
  `val_123` decimal(20,4) DEFAULT NULL COMMENT 'val_123',
  `val_124` decimal(20,4) DEFAULT NULL COMMENT 'val_124',
  `val_125` decimal(20,4) DEFAULT NULL COMMENT 'val_125',
  `val_126` decimal(20,4) DEFAULT NULL COMMENT 'val_126',
  `val_127` decimal(20,4) DEFAULT NULL COMMENT 'val_127',
  `val_128` decimal(20,4) DEFAULT NULL COMMENT 'val_128',
  `val_129` decimal(20,4) DEFAULT NULL COMMENT 'val_129',
  `val_130` decimal(20,4) DEFAULT NULL COMMENT 'val_130',
  `val_131` decimal(20,4) DEFAULT NULL COMMENT 'val_131',
  `val_132` decimal(20,4) DEFAULT NULL COMMENT 'val_132',
  `val_133` decimal(20,4) DEFAULT NULL COMMENT 'val_133',
  `val_134` decimal(20,4) DEFAULT NULL COMMENT 'val_134',
  `val_135` decimal(20,4) DEFAULT NULL COMMENT 'val_135',
  `val_136` decimal(20,4) DEFAULT NULL COMMENT 'val_136',
  `val_137` decimal(20,4) DEFAULT NULL COMMENT 'val_137',
  `val_138` decimal(20,4) DEFAULT NULL COMMENT 'val_138',
  `val_139` decimal(20,4) DEFAULT NULL COMMENT 'val_139',
  `val_140` decimal(20,4) DEFAULT NULL COMMENT 'val_140',
  `val_141` decimal(20,4) DEFAULT NULL COMMENT 'val_141',
  `val_142` decimal(20,4) DEFAULT NULL COMMENT 'val_142',
  `val_143` decimal(20,4) DEFAULT NULL COMMENT 'val_143',
  `val_144` decimal(20,4) DEFAULT NULL COMMENT 'val_144',
  `val_145` decimal(20,4) DEFAULT NULL COMMENT 'val_145',
  `val_146` decimal(20,4) DEFAULT NULL COMMENT 'val_146',
  `val_147` decimal(20,4) DEFAULT NULL COMMENT 'val_147',
  `val_148` decimal(20,4) DEFAULT NULL COMMENT 'val_148',
  `val_149` decimal(20,4) DEFAULT NULL COMMENT 'val_149',
  `val_150` decimal(20,4) DEFAULT NULL COMMENT 'val_150',
  `val_151` decimal(20,4) DEFAULT NULL COMMENT 'val_151',
  `val_152` decimal(20,4) DEFAULT NULL COMMENT 'val_152',
  `val_153` decimal(20,4) DEFAULT NULL COMMENT 'val_153',
  `val_154` decimal(20,4) DEFAULT NULL COMMENT 'val_154',
  `val_155` decimal(20,4) DEFAULT NULL COMMENT 'val_155',
  `val_156` decimal(20,4) DEFAULT NULL COMMENT 'val_156',
  `val_157` decimal(20,4) DEFAULT NULL COMMENT 'val_157',
  `val_158` decimal(20,4) DEFAULT NULL COMMENT 'val_158',
  `val_159` decimal(20,4) DEFAULT NULL COMMENT 'val_159',
  `val_160` decimal(20,4) DEFAULT NULL COMMENT 'val_160',
  `val_161` decimal(20,4) DEFAULT NULL COMMENT 'val_161',
  `val_162` decimal(20,4) DEFAULT NULL COMMENT 'val_162',
  `val_163` decimal(20,4) DEFAULT NULL COMMENT 'val_163',
  `val_164` decimal(20,4) DEFAULT NULL COMMENT 'val_164',
  `val_165` decimal(20,4) DEFAULT NULL COMMENT 'val_165',
  `val_166` decimal(20,4) DEFAULT NULL COMMENT 'val_166',
  `val_167` decimal(20,4) DEFAULT NULL COMMENT 'val_167',
  `val_168` decimal(20,4) DEFAULT NULL COMMENT 'val_168',
  `val_169` decimal(20,4) DEFAULT NULL COMMENT 'val_169',
  `val_170` decimal(20,4) DEFAULT NULL COMMENT 'val_170',
  `val_171` decimal(20,4) DEFAULT NULL COMMENT 'val_171',
  `val_172` decimal(20,4) DEFAULT NULL COMMENT 'val_172',
  `val_173` decimal(20,4) DEFAULT NULL COMMENT 'val_173',
  `val_174` decimal(20,4) DEFAULT NULL COMMENT 'val_174',
  `val_175` decimal(20,4) DEFAULT NULL COMMENT 'val_175',
  `val_176` decimal(20,4) DEFAULT NULL COMMENT 'val_176',
  `val_177` decimal(20,4) DEFAULT NULL COMMENT 'val_177',
  `val_178` decimal(20,4) DEFAULT NULL COMMENT 'val_178',
  `val_179` decimal(20,4) DEFAULT NULL COMMENT 'val_179',
  `val_180` decimal(20,4) DEFAULT NULL COMMENT 'val_180',
  `val_181` decimal(20,4) DEFAULT NULL COMMENT 'val_181',
  `val_182` decimal(20,4) DEFAULT NULL COMMENT 'val_182',
  `val_183` decimal(20,4) DEFAULT NULL COMMENT 'val_183',
  `val_184` decimal(20,4) DEFAULT NULL COMMENT 'val_184',
  `val_185` decimal(20,4) DEFAULT NULL COMMENT 'val_185',
  `val_186` decimal(20,4) DEFAULT NULL COMMENT 'val_186',
  `val_187` decimal(20,4) DEFAULT NULL COMMENT 'val_187',
  `val_188` decimal(20,4) DEFAULT NULL COMMENT 'val_188',
  `val_189` decimal(20,4) DEFAULT NULL COMMENT 'val_189',
  `val_190` decimal(20,4) DEFAULT NULL COMMENT 'val_190',
  `val_191` decimal(20,4) DEFAULT NULL COMMENT 'val_191',
  `val_192` decimal(20,4) DEFAULT NULL COMMENT 'val_192',
  `val_193` decimal(20,4) DEFAULT NULL COMMENT 'val_193',
  `val_194` decimal(20,4) DEFAULT NULL COMMENT 'val_194',
  `val_195` decimal(20,4) DEFAULT NULL COMMENT 'val_195',
  `val_196` decimal(20,4) DEFAULT NULL COMMENT 'val_196',
  `val_197` decimal(20,4) DEFAULT NULL COMMENT 'val_197',
  `val_198` decimal(20,4) DEFAULT NULL COMMENT 'val_198',
  `val_199` decimal(20,4) DEFAULT NULL COMMENT 'val_199',
  `val_200` decimal(20,4) DEFAULT NULL COMMENT 'val_200',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_subject_date_ver` (`cust_id`, `data_date`, `version`),
  KEY `idx_date_ver` (`data_date`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='客户指标结果宽表';

-- -------------------------------------------
-- 13. KPI结果表
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `KPI_RESULT` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `emp_id` varchar(32) NOT NULL COMMENT '员工工号',
  `cycle_type` varchar(20) NOT NULL COMMENT '周期类型：MONTHLY/QUARTERLY',
  `cycle_date` date NOT NULL COMMENT '周期日期(如月末)',
  `as_of_date` date NOT NULL COMMENT '计算基准日(每日一算区分键)',
  `data_version` varchar(32) NOT NULL COMMENT '指标数据版本',
  `kpi_total_score` decimal(10,4) NOT NULL COMMENT 'KPI总分',
  `detail_json` longtext COMMENT '明细(JSON，可选)',
  `calculated_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_emp_cycle_asof` (`emp_id`, `cycle_type`, `cycle_date`, `as_of_date`),
  KEY `idx_as_of_date` (`as_of_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='KPI结果表';

-- -------------------------------------------
-- 14. 客户业绩分配关系
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `CUST_ALLOC_RELATION` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `cust_id` varchar(32) NOT NULL COMMENT '客户ID',
  `alloc_dim` varchar(16) NOT NULL COMMENT '调整维度：RULE/ACCOUNT',
  `biz_kind` varchar(32) DEFAULT NULL COMMENT '业务种类',
  `account_no` varchar(64) DEFAULT NULL COMMENT '账号(账号维度必填)',
  `emp_id` varchar(32) NOT NULL COMMENT '员工工号',
  `ratio` decimal(5,2) NOT NULL COMMENT '比例(0-100)',
  `effective_date` date NOT NULL COMMENT '生效日期',
  `end_date` date DEFAULT NULL COMMENT '失效日期',
  `source_batch_id` varchar(64) DEFAULT NULL COMMENT '来源批次号(可选)',
  `source_process_date` date DEFAULT NULL COMMENT '来源业务日期(可选)',
  `created_by` varchar(32) NOT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_cust_id` (`cust_id`),
  KEY `idx_emp_id` (`emp_id`),
  KEY `idx_effective_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='客户业绩分配关系';

-- -------------------------------------------
-- 15. 分配关系调整申请
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_ALLOC_ADJUST_APPLY` (
  `id` varchar(32) NOT NULL COMMENT '申请ID',
  `apply_no` varchar(100) DEFAULT NULL COMMENT '申请编号',
  `cust_id` varchar(32) NOT NULL COMMENT '客户ID',
  `alloc_dim` varchar(16) NOT NULL COMMENT '维度：RULE/ACCOUNT',
  `biz_kind` varchar(32) DEFAULT NULL COMMENT '业务种类',
  `account_no` varchar(64) DEFAULT NULL COMMENT '账号(可选)',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/IN_APPROVAL/APPROVED/REJECTED',
  `business_key` varchar(100) DEFAULT NULL COMMENT '流程业务键',
  `process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `owner_org_id` varchar(50) NOT NULL COMMENT '归属机构',
  `remark` text COMMENT '备注',
  `created_by` varchar(32) NOT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_cust_id` (`cust_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='分配关系调整申请';

-- -------------------------------------------
-- 16. 分配关系调整明细
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_ALLOC_ADJUST_ITEM` (
  `id` varchar(32) NOT NULL COMMENT '项ID',
  `apply_id` varchar(32) NOT NULL COMMENT '申请ID',
  `emp_id` varchar(32) NOT NULL COMMENT '员工工号',
  `ratio` decimal(5,2) NOT NULL COMMENT '比例(0-100)',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_emp` (`apply_id`, `emp_id`),
  KEY `idx_apply_id` (`apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='分配关系调整明细';

-- -------------------------------------------
-- 17. 目标修正申请
-- -------------------------------------------
CREATE TABLE IF NOT EXISTS `PERF_TARGET_ADJUST_APPLY` (
  `id` varchar(32) NOT NULL COMMENT '申请ID',
  `plan_id` varchar(32) NOT NULL COMMENT '目标方案ID',
  `subject_type` varchar(20) NOT NULL COMMENT '对象类型：EMP/ORG',
  `subject_id` varchar(50) NOT NULL COMMENT '对象ID',
  `cycle_key` varchar(20) NOT NULL COMMENT '周期键',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/IN_APPROVAL/APPROVED/REJECTED',
  `business_key` varchar(100) DEFAULT NULL COMMENT '流程业务键',
  `process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `owner_org_id` varchar(50) NOT NULL COMMENT '归属机构',
  `remark` text COMMENT '备注',
  `created_by` varchar(32) NOT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `updated_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='目标修正申请';
