CREATE TABLE IF NOT EXISTS SUPPORT_REQUEST (
  id                     VARCHAR(32)    NOT NULL,
  request_no             VARCHAR(100)   DEFAULT NULL,
  submit_group_id        VARCHAR(64)    DEFAULT NULL,
  cust_id                VARCHAR(32)    NOT NULL,
  source_touch_task_id   VARCHAR(32)    DEFAULT NULL,
  product_id             VARCHAR(64)    DEFAULT NULL,
  support_dept_id        VARCHAR(50)    DEFAULT NULL,
  other_demand           TEXT           DEFAULT NULL,
  dispatch_emp_id        VARCHAR(32)    DEFAULT NULL,
  dispatch_time          TIMESTAMP      DEFAULT NULL,
  assigned_emp_id        VARCHAR(32)    DEFAULT NULL,
  status                 VARCHAR(20)    NOT NULL DEFAULT 'DRAFT',
  business_key           VARCHAR(100)   DEFAULT NULL,
  process_instance_id    VARCHAR(64)    DEFAULT NULL,
  owner_org_id           VARCHAR(50)    NOT NULL,
  created_by             VARCHAR(32)    NOT NULL,
  created_time           TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  updated_by             VARCHAR(32)    DEFAULT NULL,
  updated_time           TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  deleted                INT            NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
