-- ============================================================
-- Combined H2 Schema for Bootstrap E2E Tests
-- All tables: auth + governance + workflow
-- ============================================================

-- ====== AUTH TABLES ======

CREATE TABLE IF NOT EXISTS PT_USER (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(200) NOT NULL,
    USERCHNNAME VARCHAR(200) NOT NULL,
    PWD VARCHAR(64) DEFAULT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    ISEXPIRED INT DEFAULT 0,
    ISLOCKED INT DEFAULT 0,
    PASS_WRONG_COUNT INT DEFAULT 0,
    ISENABLED INT DEFAULT 1,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_AUTHOR VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AUTHOR VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL,
    PWD_UPDATE_TIME DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PT_ROLE (
    ROLE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ROLE_CODE VARCHAR(20) NOT NULL,
    ROLE_CHNAME VARCHAR(100) NOT NULL,
    RECORD_STATUS INT DEFAULT 0,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PT_RESOURCE (
    RESOURCE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    RESOURCE_URL VARCHAR(256) NOT NULL,
    RESOURCE_METHOD VARCHAR(10) NOT NULL,
    MENU_NAME VARCHAR(256) NOT NULL,
    MENU_ICON_URL VARCHAR(256) DEFAULT NULL,
    MENU_RANK_NO INT DEFAULT 0,
    ISMENU INT DEFAULT 0,
    MENU_ENDFLAG VARCHAR(10) DEFAULT '0',
    PARENT_RESOURCE_ID VARCHAR(60) DEFAULT NULL,
    STATUS INT DEFAULT 0,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PT_USER_ROLE (
    USER_ID VARCHAR(50) NOT NULL,
    ROLE_ID VARCHAR(50) NOT NULL,
    DEFAULT_ASSIGN INT DEFAULT 0,
    INHERIT_ASSIGN INT DEFAULT 0,
    GROUP_ASSING INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS PT_ROLE_RESOURCE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_ID VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(20) NOT NULL,
    SYS_CODE VARCHAR(10) DEFAULT 'PLATFORM',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PT_ROLE_BIZ_SCOPE (
    ID VARCHAR(32) NOT NULL PRIMARY KEY,
    ROLE_ID VARCHAR(50) NOT NULL,
    BIZ_TYPE VARCHAR(50) NOT NULL,
    DATA_SCOPE VARCHAR(50) NOT NULL,
    RECORD_STATUS INT DEFAULT 0,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_USER VARCHAR(50) DEFAULT NULL,
    REMARK VARCHAR(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS EXT_ORG_INFO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORG_CODE VARCHAR(20) NOT NULL UNIQUE,
    ORG_NAME VARCHAR(200) NOT NULL,
    ORG_LEVEL INT DEFAULT NULL,
    P_ID VARCHAR(20) DEFAULT NULL,
    ORGAN_STATE INT DEFAULT 0,
    ADM_DIVISION_CODE VARCHAR(20) DEFAULT NULL,
    ADM_DIVISION_NAME VARCHAR(255) DEFAULT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_USER VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS EXT_USER_ORG (
    USER_ID VARCHAR(50) NOT NULL,
    ORG_CODE VARCHAR(20) NOT NULL,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, ORG_CODE)
);

-- ====== GOVERNANCE TABLES ======

CREATE TABLE IF NOT EXISTS sys_dict (
    id VARCHAR(32) PRIMARY KEY,
    dict_type VARCHAR(100) NOT NULL,
    dict_code VARCHAR(100) NOT NULL,
    dict_label VARCHAR(200) NOT NULL,
    dict_value VARCHAR(500) NOT NULL,
    sort_order INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    remark VARCHAR(500) DEFAULT NULL,
    created_by VARCHAR(32) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(32) DEFAULT NULL,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_config_kv (
    id VARCHAR(32) PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value VARCHAR(2000) NOT NULL,
    value_type VARCHAR(20) DEFAULT 'STRING',
    status VARCHAR(20) DEFAULT 'ACTIVE',
    remark VARCHAR(500) DEFAULT NULL,
    created_by VARCHAR(32) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(32) DEFAULT NULL,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_calendar_day (
    `day` DATE PRIMARY KEY,
    is_workday INT DEFAULT 1,
    remark VARCHAR(200) DEFAULT NULL,
    created_by VARCHAR(32) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(32) DEFAULT NULL,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id VARCHAR(32) PRIMARY KEY,
    trace_id VARCHAR(64) DEFAULT NULL,
    emp_id VARCHAR(32) NOT NULL,
    emp_name VARCHAR(100) DEFAULT NULL,
    biz_type VARCHAR(50) DEFAULT NULL,
    biz_action VARCHAR(50) DEFAULT NULL,
    resource_url VARCHAR(500) DEFAULT NULL,
    request_method VARCHAR(20) DEFAULT NULL,
    request_params TEXT,
    response_status INT DEFAULT NULL,
    error_msg TEXT,
    ip_address VARCHAR(50) DEFAULT NULL,
    user_agent VARCHAR(500) DEFAULT NULL,
    execution_time INT DEFAULT NULL,
    reason VARCHAR(500) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_notification (
    id VARCHAR(32) PRIMARY KEY,
    emp_id VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    notify_type VARCHAR(50) DEFAULT NULL,
    biz_type VARCHAR(50) DEFAULT NULL,
    biz_id VARCHAR(100) DEFAULT NULL,
    link_url VARCHAR(500) DEFAULT NULL,
    `is_read` TINYINT(1) DEFAULT 0,
    read_time DATETIME DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file_object (
    id VARCHAR(32) PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT DEFAULT NULL,
    file_type VARCHAR(100) DEFAULT NULL,
    storage_path VARCHAR(500) NOT NULL,
    bucket_name VARCHAR(100) DEFAULT NULL,
    md5_hash VARCHAR(64) DEFAULT NULL,
    uploaded_by VARCHAR(32) DEFAULT NULL,
    uploaded_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biz_file_rel (
    id VARCHAR(32) PRIMARY KEY,
    biz_type VARCHAR(32),
    biz_id VARCHAR(100),
    file_object_id VARCHAR(32),
    file_role VARCHAR(32),
    created_by VARCHAR(32),
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_job_conf (
    id VARCHAR(32) PRIMARY KEY,
    job_key VARCHAR(100) NOT NULL UNIQUE,
    job_name VARCHAR(100),
    cron_expr VARCHAR(64),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    allow_manual_trigger TINYINT(1) DEFAULT 1,
    last_run_time DATETIME DEFAULT NULL,
    next_run_time DATETIME DEFAULT NULL,
    remark VARCHAR(500) DEFAULT NULL,
    created_by VARCHAR(32) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(32) DEFAULT NULL,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_job_run_log (
    id VARCHAR(32) PRIMARY KEY,
    job_id VARCHAR(32),
    trigger_type VARCHAR(20) DEFAULT 'SCHEDULED',
    reason VARCHAR(500) DEFAULT NULL,
    start_time DATETIME,
    end_time DATETIME,
    status VARCHAR(20) DEFAULT 'RUNNING',
    error_msg TEXT,
    created_by VARCHAR(32) DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ====== WORKFLOW TABLES ======

CREATE TABLE IF NOT EXISTS biz_process_map (
    id VARCHAR(32) PRIMARY KEY,
    business_key VARCHAR(100) NOT NULL UNIQUE,
    biz_type VARCHAR(50) NOT NULL,
    biz_id VARCHAR(100) NOT NULL,
    process_definition_key VARCHAR(100) NOT NULL,
    process_instance_id VARCHAR(64) NOT NULL UNIQUE,
    start_user VARCHAR(32) NOT NULL,
    current_assignee VARCHAR(32) DEFAULT NULL,
    candidate_groups TEXT,
    title VARCHAR(200) DEFAULT NULL,
    process_status VARCHAR(50) DEFAULT 'RUNNING',
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    end_time DATETIME DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wf_node_candidate_conf (
    id VARCHAR(32) PRIMARY KEY,
    process_definition_key VARCHAR(100) NOT NULL,
    node_key VARCHAR(100) NOT NULL,
    candidate_type VARCHAR(50) NOT NULL,
    candidate_value TEXT,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wf_node_form_conf (
    id VARCHAR(32) PRIMARY KEY,
    process_definition_key VARCHAR(100) NOT NULL,
    node_key VARCHAR(100) NOT NULL,
    form_fields TEXT,
    editable_fields TEXT,
    required_fields TEXT,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wf_timeout_rule (
    id VARCHAR(32) PRIMARY KEY,
    process_definition_key VARCHAR(100) NOT NULL,
    node_key VARCHAR(100) NOT NULL,
    timeout_hours INT NOT NULL,
    warning_hours INT DEFAULT NULL,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
