#!/usr/bin/env bash
# 仅开发态 mock，非 yiti_test、非真实后端联调。
# 用法：在已通过 playwright-cli 打开同名 session 后执行：
#   bash ROUND3-development-mock-routes.sh screen-round3-proof
set -euo pipefail

session="${1:-screen-round3-proof}"
pc() { npx playwright-cli "-s=${session}" "$@"; }

pc route '**/favicon.svg' --status 200 --content-type image/svg+xml --body '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"/>'
pc route '**/api/auth/current-user' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-auth-current","data":{"empId":"u-round3-proof","username":"u-round3-proof","displayName":"开发态 Mock 管理员","mainOrgCode":"ORG_001","mainOrgName":"西安管理行","roles":[{"roleId":"9001","roleCode":"SYS_ADMIN","roleChName":"系统管理员"}],"isSystemAdmin":true}}'
pc route '**/api/auth/my-menus' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-menus","data":[{"resourceId":"M_REPORT","resourceUrl":"/report","menuName":"报表分析","children":[{"resourceId":"M_SCREEN_DS","resourceUrl":"/screen-admin/datasources","menuName":"大屏数据源"},{"resourceId":"M_SCREEN_DESIGN","resourceUrl":"/screen-admin/designer","menuName":"大屏设计器"}]}]}'
pc route '**/api/auth/permissions' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-permissions","data":{"resourceUrls":["/api/screen/admin/screens","/api/screen/admin/canvas/101","/api/screen/admin/canvas/save","/api/screen/admin/canvas/publish","/api/screen/admin/canvas/rollback","/api/screen/admin/canvas/101/publish-logs","/api/screen/admin/screens/101/metadata","/api/screen/admin/screens/101/access-roles","/api/screen/admin/datasources","/api/admin/org-groups","/api/admin/org-profiles","/api/admin/roles/all"],"roleCodes":["SYS_ADMIN"],"isSystemAdmin":true}}'
pc route '**/api/notifications/unread-count' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-notifications","data":0}'
pc route '**/api/perf/metrics*' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-metrics","data":[{"metricCode":"M_ORG_A","metricName":"机构指标A","baseDim":"ORG"}]}'
pc route '**/api/screen/admin/kpi-schemes' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-kpi-schemes","data":[]}'
pc route '**/api/admin/org-groups' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-org-groups","data":[{"groupCode":"G_XIAN_DEMO","groupName":"西安测试机构组","status":"ACTIVE","groupPurpose":"REPORT_SCREEN","memberOrgCodes":["610101"]}]}'
pc route '**/api/screen/admin/datasources*' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-datasources","data":[{"id":72,"dsCode":"DS_XIAN_ORG","dsName":"西安机构宽表","remark":"开发态 mock","bizLine":"CORP","dsType":"TIMESERIES","sourceKind":"WIDE_TABLE","status":"ACTIVE","configJson":"{\"schemaVersion\":2,\"table\":\"ORG_INDEX_RESULT\",\"metrics\":[{\"metricCode\":\"M_ORG_A\"}],\"scopeMode\":\"NAMED_GROUP\"}","timeParamJson":"[]","draftReferenceScreenCodes":[],"publishedReferenceScreenCodes":[]}]}'
pc route '**/api/screen/admin/screens' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-screens","data":[{"id":101,"screenCode":"SCR_XIAN_MOCK","screenName":"西安复合演示屏","viewLevel":"BRANCH","bizLine":"CORP","orgScopeMode":"NAMED_GROUP","orgGroupCode":"G_XIAN_DEMO","canvasVersion":7,"status":"ACTIVE","themeJson":"{}"}]}'
pc route '**/api/screen/admin/canvas/101' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-canvas","data":{"screenId":101,"screenCode":"SCR_XIAN_MOCK","canvasVersion":7,"publishStatus":1,"canvasStyleJson":"{\"schemaVersion\":2,\"designWidth\":1920,\"designHeight\":1080,\"background\":\"#050e2b\",\"adaptor\":\"keepProportion\",\"themeOverride\":{}}","canvasDraftJson":"{\"schemaVersion\":2,\"components\":[],\"bindSnapshots\":{}}","blocks":[]}}'
pc route '**/api/screen/admin/canvas/save' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-canvas-save","data":{"screenId":101,"canvasVersion":7}}'
pc route '**/api/screen/admin/canvas/publish' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-publish","data":null}'
pc route '**/api/screen/admin/canvas/rollback' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-rollback","data":null}'
pc route '**/api/screen/admin/canvas/101/publish-logs' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-publish-logs","data":[{"id":501,"publishedAt":"2026-08-12 09:00:00"}]}'
pc route '**/api/screen/admin/screens/101/metadata' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-metadata","data":null}'
pc route '**/api/admin/org-profiles*' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-org-profiles","data":[{"orgCode":"610101","orgName":"高新支行","cityCode":"610100","operatingLevel":"PRIMARY","coordSys":"GCJ02","lng":108.94,"lat":34.23,"status":"ACTIVE"}]}'
pc route '**/api/admin/roles/all*' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-roles","data":[{"roleCode":"ROLE_XIAN","roleChName":"西安经营角色"}]}'
pc route '**/api/screen/admin/screens/101/access-roles' --status 200 --content-type application/json --body '{"code":"0","message":"success","traceId":"round3-proof-access-roles","data":["ROLE_XIAN"]}'
